targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: gravity|lib/data/gql/schema.graphql
          global_enum_fallbacks: true
          output_dir: 'g'
          when_extensions:
            when: true
            maybeWhen: true
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: gravity|lib/data/gql/schema.graphql
          output_dir: 'g'
