targets:
  $default:
    builders:

      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/**_screen.dart

      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/app/router/root_router.dart

      freezed:
        options:
          # This can significantly speed up code-generation.
          format: true
          copy_with: true
          equal: true
          when: false
          map: false

      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: tentura|lib/data/gql/schema.graphql
          # global_enum_fallbacks: true
          vars_create_factories: true
          output_dir: "_g"
          # when_extensions:
          #   when: true
          #   maybeWhen: true

          type_overrides:
            timestamptz:
              name: DateTime

            tstzrange:
              name: DateTimeRange
              import: "package:flutter/material.dart"

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: tentura|lib/data/gql/schema.graphql
          output_dir: "_g"

          type_overrides:
            timestamptz:
              name: DateTime

            tstzrange:
              name: DateTimeRange
              import: "package:flutter/material.dart"

          custom_serializers:
            - import: "package:tentura/data/gql/timestamptz_serializer.dart"
              name: TimestamptzSerializer

            - import: "package:tentura/data/gql/tstzrange_serializer.dart"
              name: TstzrangeSerializer
