targets:
  $default:
    builders:

      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: tentura|lib/data/gql/schema.graphql
          global_enum_fallbacks: true
          output_dir: "_g"
          when_extensions:
            when: true
            maybeWhen: true

          type_overrides:
            timestamptz:
              name: DateTime

            tstzrange:
              name: DateTimeRange
              import: "package:flutter/material.dart"

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: tentura|lib/data/gql/schema.graphql
          output_dir: "_g"

          type_overrides:
            timestamptz:
              name: DateTime

            tstzrange:
              name: DateTimeRange
              import: "package:flutter/material.dart"

          custom_serializers:
            - import: "package:tentura/data/gql/timestamptz_serializer.dart"
              name: TimestamptzSerializer

            - import: "package:tentura/data/gql/tstzrange_serializer.dart"
              name: TstzrangeSerializer
