name: tentura_root
publish_to: none

version: 0.0.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  latlong2: ^0.9.1

dev_dependencies:
  very_good_analysis: ^7.0.0

flutter:
  generate: true
