name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 0.7.6

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter
  nil: ^1.1.1
  intl: ^0.19.0
  get_it: ^7.7.0
  latlong2: ^0.9.1
  injectable: ^2.4.4
  auto_route: ^9.2.2
  collection: ^1.18.0
  built_value: ^8.9.2
  flutter_bloc: ^8.1.6
  synchronized: ^3.3.0
  sentry_flutter: ^8.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Platform related
  geocoding: ^3.0.0
  share_plus: ^10.0.2
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3
  flutter_secure_storage: ^9.2.2

  # UI related
  readmore: ^3.0.0
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.10
  dots_indicator: ^3.0.0
  pretty_qr_code: ^3.3.0
  vector_graphics: ^1.1.11
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.0
  force_directed_graphview: ^0.6.2
  flutter_map_cancellable_tile_provider: ^3.0.0

  # Local
  tentura_sdk:
    path: packages/tentura_sdk
  share_handler_multi:
    path: packages/share_handler_multi

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.11
  ferry_generator: ^0.12.0
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  fonts:
    - family: Tentura
      fonts:
        - asset: assets/fonts/tentura-icons.ttf
  assets:
    - assets/images/
    - assets/intro/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true
