name: gravity
description: 'Gravity for a social ranking'
publish_to: 'none'

version: 0.0.5+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  go_router: ^9.0.3
  get_it: ^7.6.0
  intl: ^0.18.0

  firebase_ui_oauth_google: ^1.2.5
  firebase_storage: ^11.2.5
  firebase_ui_auth: ^1.6.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0

  ferry_hive_store: ^0.5.1
  graphql_flutter: ^5.1.2
  gql_http_link: ^1.0.1
  ferry_flutter: ^0.8.1
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  built_value: ^8.6.1
  equatable: ^2.0.5
  ferry: ^0.14.2+1

  cached_network_image: ^3.2.3
  image_picker: ^1.0.1
  flutter_map: ^5.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  latlong2: ^0.9.0
  # image: ^4.0.17

  sentry_flutter: ^7.8.0
  # sentry_logging: ^7.8.0
  # sentry_link: ^0.3.0
  # logging: ^1.2.0

  force_directed_graphview:
    git: "https://github.com/cupofme/force_directed_graphview.git"

dependency_overrides:
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
  ferry_generator: ^0.8.1
  build_runner: ^2.0.2
  gql_exec: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
