name: gravity
description: 'Gravity for a social ranking'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  go_router: ^8.0.1
  get_it: ^7.6.0

  firebase_ui_oauth_google: ^1.2.2
  firebase_storage: ^11.2.3
  firebase_ui_auth: ^1.4.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  graphql_flutter: ^5.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  cached_network_image: ^3.2.3
  # ai_barcode_scanner: ^0.0.6
  # mobile_scanner: ^3.2.0
  # vector_graphics: ^1.1.6
  # google_fonts: ^4.0.4
  # flutter_svg: ^2.0.6
  # qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
