name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 0.6.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  nil: ^1.1.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  equatable: ^2.0.5
  go_router: ^14.1.3
  collection: ^1.18.0
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5

  # Platform related
  hive: ^2.2.3
  geocoding: ^3.0.0
  share_plus: ^9.0.0
  geolocator: ^12.0.0
  path_provider: ^2.1.3
  mobile_scanner: ^5.1.1
  flutter_secure_storage: ^9.2.2

  # API related
  http: ^1.2.1
  ferry: ^0.16.0
  built_value: ^8.9.2
  fresh_graphql: ^0.6.0
  gql_http_link: ^1.0.1
  ed25519_edwards: ^0.3.1
  ferry_hive_store: ^0.5.2

  # UI related
  qr_flutter: ^4.1.0
  flutter_map: ^7.0.0
  flutter_svg: ^2.0.10
  image_picker: ^1.1.1
  # pretty_qr_code: ^3.3.0
  vector_graphics: ^1.1.11
  cached_network_image: ^3.3.1
  force_directed_graphview: ^0.6.2
  # infinite_scroll_pagination: ^4.0.0

  # Logging & etc
  # logger: ^2.3.0
  # logging: ^1.2.0
  # sentry_link: ^0.4.0
  sentry_flutter: ^8.2.0
  # sentry_logging: ^7.8.0
  # logging_appenders: ^1.1.0

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  ferry_generator: ^0.10.0
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo1024.png"
