name: hydrated_bloc
description: An extension to the bloc state management library which automatically persists and restores bloc states.
version: 10.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  hive: ^2.2.3
  meta: ^1.3.0
  synchronized: ^3.0.0
