name: preferences_repository
description: Dart package which manages the application preferences domain.
publish_to: none

version: 0.0.1+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
