/// Request plan («либретто», #220): storage constants and limits.
///
/// Plan steps are `coordination_item` rows with kind
/// [BeaconPlanConsts.stepKind] (m0223). Markers 13..16 live in
/// `beacon_room_consts.dart`, activity types 21..24 in
/// `beacon_activity_event_consts.dart`.
abstract final class BeaconPlanConsts {
  /// `coordination_item.kind` of a plan step. Legacy kind 1 readers never
  /// see it.
  static const stepKind = 6;

  /// `coordination_item.status` of a live step.
  static const stepStatusLive = 0;

  /// `coordination_item.status` of a removed (soft-deleted) step.
  static const stepStatusRemoved = 3;

  /// Step ids are generated by the client so a draft survives a conflict.
  static const stepIdPrefix = 'PS';

  static const maxSteps = 100;
  static const maxTitleLength = 120;
  static const maxDescriptionLength = 1000;
  static const maxCommentLength = 280;

  /// Plan writes per actor within [rateWindow].
  static const rateMax = 20;
  static const rateWindow = Duration(seconds: 60);

  /// Ticks within this window coalesce into the tail marker-14 line.
  static const tickCoalesceWindow = Duration(minutes: 30);

  /// Max changes / ticks listed in one system line payload.
  static const systemLineMaxEntries = 20;

  /// The author hears about a late step this long after it became overdue.
  static const authorLateDelay = Duration(minutes: 30);

  /// A sweep phase older than this fires without push or email.
  static const sweepStaleness = Duration(minutes: 10);

  /// Reminders are skipped when the start is closer than this.
  static const reminderMinLead = Duration(minutes: 2);

  static final stepIdPattern = RegExp(r'^PS[0-9a-f]{12}$');
}

/// `beacon_plan_revision.kind`.
abstract final class PlanRevisionKind {
  static const created = 0;
  static const edited = 1;
  static const restored = 2;
  static const copied = 3;
  static const cantMake = 4;
  static const unassignedOnLeave = 5;
}

/// Wire values of the «Не успеваю» options.
abstract final class PlanCantMakeOption {
  static const reschedule = 'reschedule';
  static const handover = 'handover';
  static const chat = 'chat';
}
