name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

  tentura:
    path: ../

dev_dependencies:
  build_runner: ^2.4.4
  very_good_analysis: ^6.0.0
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Tentura
      fonts:
        - asset: assets/fonts/tentura-icons.ttf
