name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

version: 0.0.1+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ed25519_edwards: ^0.3.1
  http: ^1.1.0
