// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/capability_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/port/person_capability_event_repository_port.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePersonCapabilityCuesRow_0 extends _i1.SmartFake
    implements _i2.PersonCapabilityCuesRow {
  _FakePersonCapabilityCuesRow_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PersonCapabilityEventRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonCapabilityEventRepositoryPort extends _i1.Mock
    implements _i2.PersonCapabilityEventRepositoryPort {
  MockPersonCapabilityEventRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertPrivateLabels({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> fetchPrivateLabels({
    required String? observerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> insertForwardReasons({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertForwardReasons, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
              #note: note,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertCommitRole({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCommitRole, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertCloseAcknowledgements({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCloseAcknowledgements, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.PersonCapabilityCuesRow> fetchCues({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCues, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<_i2.PersonCapabilityCuesRow>.value(
              _FakePersonCapabilityCuesRow_0(
                this,
                Invocation.method(#fetchCues, [], {
                  #viewerId: viewerId,
                  #subjectId: subjectId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.PersonCapabilityCuesRow>);

  @override
  _i3.Future<void> insertTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.ViewerVisibleCapabilityRow>>
  fetchDeduplicatedCapabilities({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeduplicatedCapabilities, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<List<_i2.ViewerVisibleCapabilityRow>>.value(
              <_i2.ViewerVisibleCapabilityRow>[],
            ),
          )
          as _i3.Future<List<_i2.ViewerVisibleCapabilityRow>>);

  @override
  _i3.Future<List<_i2.ForwardReasonRow>> fetchForwardReasonsByBeaconId({
    required String? beaconId,
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForwardReasonsByBeaconId, [], {
              #beaconId: beaconId,
              #viewerId: viewerId,
            }),
            returnValue: _i3.Future<List<_i2.ForwardReasonRow>>.value(
              <_i2.ForwardReasonRow>[],
            ),
          )
          as _i3.Future<List<_i2.ForwardReasonRow>>);
}
