// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/capability_projection_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/capability/capability_evidence_models.dart'
    as _i2;
import 'package:tentura_server/domain/port/capability_cell_port.dart' as _i5;
import 'package:tentura_server/domain/port/capability_own_evidence_port.dart'
    as _i6;
import 'package:tentura_server/domain/port/pair_block_query_port.dart' as _i8;
import 'package:tentura_server/domain/port/routing_mute_port.dart' as _i7;
import 'package:tentura_server/domain/port/witness_window_port.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRawWindowFacts_0 extends _i1.SmartFake
    implements _i2.RawWindowFacts {
  _FakeRawWindowFacts_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WitnessWindowPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockWitnessWindowPort extends _i1.Mock implements _i3.WitnessWindowPort {
  MockWitnessWindowPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RawWindowFacts> rawWindowFacts({
    required String? egoId,
    required String? normalizedContext,
    required int? topK,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rawWindowFacts, [], {
              #egoId: egoId,
              #normalizedContext: normalizedContext,
              #topK: topK,
            }),
            returnValue: _i4.Future<_i2.RawWindowFacts>.value(
              _FakeRawWindowFacts_0(
                this,
                Invocation.method(#rawWindowFacts, [], {
                  #egoId: egoId,
                  #normalizedContext: normalizedContext,
                  #topK: topK,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.RawWindowFacts>);

  @override
  _i4.Future<void> storeWindow({
    required String? egoId,
    required String? normalizedContext,
    required List<_i2.WitnessWeight>? weights,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeWindow, [], {
              #egoId: egoId,
              #normalizedContext: normalizedContext,
              #weights: weights,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.WitnessWeight>> cachedWindow({
    required String? egoId,
    required String? normalizedContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cachedWindow, [], {
              #egoId: egoId,
              #normalizedContext: normalizedContext,
            }),
            returnValue: _i4.Future<List<_i2.WitnessWeight>>.value(
              <_i2.WitnessWeight>[],
            ),
          )
          as _i4.Future<List<_i2.WitnessWeight>>);

  @override
  _i4.Future<void> invalidateFor({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#invalidateFor, [], {#userId: userId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bumpMrEpoch() =>
      (super.noSuchMethod(
            Invocation.method(#bumpMrEpoch, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CapabilityCellPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapabilityCellPort extends _i1.Mock
    implements _i5.CapabilityCellPort {
  MockCapabilityCellPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.WitnessCellRow>> fetchCells({
    required List<String>? subjectIds,
    required List<String>? tagSlugs,
    required List<_i2.WitnessWeight>? admittedWitnesses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCells, [], {
              #subjectIds: subjectIds,
              #tagSlugs: tagSlugs,
              #admittedWitnesses: admittedWitnesses,
            }),
            returnValue: _i4.Future<List<_i2.WitnessCellRow>>.value(
              <_i2.WitnessCellRow>[],
            ),
          )
          as _i4.Future<List<_i2.WitnessCellRow>>);

  @override
  _i4.Future<void> rebuildCell(_i2.CellRef? ref) =>
      (super.noSuchMethod(
            Invocation.method(#rebuildCell, [ref]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.CellRef>> claimExpiredCells({
    required int? limit,
    required String? leaseOwner,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#claimExpiredCells, [], {
              #limit: limit,
              #leaseOwner: leaseOwner,
            }),
            returnValue: _i4.Future<List<_i2.CellRef>>.value(<_i2.CellRef>[]),
          )
          as _i4.Future<List<_i2.CellRef>>);
}

/// A class which mocks [CapabilityOwnEvidencePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapabilityOwnEvidencePort extends _i1.Mock
    implements _i6.CapabilityOwnEvidencePort {
  MockCapabilityOwnEvidencePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.OwnEvidenceRow>> fetchOwnEvidence({
    required String? egoId,
    required List<String>? subjectIds,
    required List<String>? tagSlugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOwnEvidence, [], {
              #egoId: egoId,
              #subjectIds: subjectIds,
              #tagSlugs: tagSlugs,
            }),
            returnValue: _i4.Future<List<_i2.OwnEvidenceRow>>.value(
              <_i2.OwnEvidenceRow>[],
            ),
          )
          as _i4.Future<List<_i2.OwnEvidenceRow>>);

  @override
  _i4.Future<List<_i2.TombstoneRef>> fetchTombstones({
    required String? egoId,
    required List<String>? subjectIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTombstones, [], {
              #egoId: egoId,
              #subjectIds: subjectIds,
            }),
            returnValue: _i4.Future<List<_i2.TombstoneRef>>.value(
              <_i2.TombstoneRef>[],
            ),
          )
          as _i4.Future<List<_i2.TombstoneRef>>);
}

/// A class which mocks [RoutingMutePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutingMutePort extends _i1.Mock implements _i7.RoutingMutePort {
  MockRoutingMutePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, Set<String>>> mutedSlugsFor({
    required List<String>? subjectIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mutedSlugsFor, [], {#subjectIds: subjectIds}),
            returnValue: _i4.Future<Map<String, Set<String>>>.value(
              <String, Set<String>>{},
            ),
          )
          as _i4.Future<Map<String, Set<String>>>);

  @override
  _i4.Future<Set<String>> mutedSlugsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#mutedSlugsForUser, [userId]),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> setMute({
    required String? userId,
    required String? tagSlug,
    required bool? muted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setMute, [], {
              #userId: userId,
              #tagSlug: tagSlug,
              #muted: muted,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PairBlockQueryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPairBlockQueryPort extends _i1.Mock
    implements _i8.PairBlockQueryPort {
  MockPairBlockQueryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Set<(String, String)>> blockedPairsAmong({
    required Set<String>? userIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#blockedPairsAmong, [], {#userIds: userIds}),
            returnValue: _i4.Future<Set<(String, String)>>.value(
              <(String, String)>{},
            ),
          )
          as _i4.Future<Set<(String, String)>>);
}
