// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/capability_routing_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/capability/capability_evidence_models.dart'
    as _i4;
import 'package:tentura_server/domain/port/capability_evidence_port.dart'
    as _i2;
import 'package:tentura_server/domain/port/routing_mute_port.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CapabilityEvidencePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapabilityEvidencePort extends _i1.Mock
    implements _i2.CapabilityEvidencePort {
  MockCapabilityEvidencePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reconcileForwardReasons({
    required String? forwardEdgeId,
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reconcileForwardReasons, [], {
              #forwardEdgeId: forwardEdgeId,
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> emitOutcomeEvidenceBatch({
    required String? beaconId,
    required List<_i4.OutcomeEmission>? emissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#emitOutcomeEvidenceBatch, [], {
              #beaconId: beaconId,
              #emissions: emissions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revokeOutcomeEvidence({
    required String? beaconId,
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#revokeOutcomeEvidence, [], {
              #beaconId: beaconId,
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertSeedAttestation({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSeedAttestation, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RoutingMutePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutingMutePort extends _i1.Mock implements _i5.RoutingMutePort {
  MockRoutingMutePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, Set<String>>> mutedSlugsFor({
    required List<String>? subjectIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mutedSlugsFor, [], {#subjectIds: subjectIds}),
            returnValue: _i3.Future<Map<String, Set<String>>>.value(
              <String, Set<String>>{},
            ),
          )
          as _i3.Future<Map<String, Set<String>>>);

  @override
  _i3.Future<Set<String>> mutedSlugsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#mutedSlugsForUser, [userId]),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);

  @override
  _i3.Future<void> setMute({
    required String? userId,
    required String? tagSlug,
    required bool? muted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setMute, [], {
              #userId: userId,
              #tagSlug: tagSlug,
              #muted: muted,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
