// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/commitment_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/entity/beacon_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/commitment_entity.dart' as _i7;
import 'package:tentura_server/domain/entity/gql_public/commitment_with_coordination_row.dart'
    as _i9;
import 'package:tentura_server/domain/entity/inbox_item_entity.dart' as _i11;
import 'package:tentura_server/domain/port/beacon_repository_port.dart' as _i4;
import 'package:tentura_server/domain/port/commitment_repository_port.dart'
    as _i6;
import 'package:tentura_server/domain/port/coordination_repository_port.dart'
    as _i8;
import 'package:tentura_server/domain/port/inbox_repository_port.dart' as _i10;
import 'package:tentura_server/domain/port/person_capability_event_repository_port.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBeaconEntity_0 extends _i1.SmartFake implements _i2.BeaconEntity {
  _FakeBeaconEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonCapabilityCuesRow_1 extends _i1.SmartFake
    implements _i3.PersonCapabilityCuesRow {
  _FakePersonCapabilityCuesRow_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeaconRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRepositoryPort extends _i1.Mock
    implements _i4.BeaconRepositoryPort {
  MockBeaconRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BeaconEntity> createBeacon({
    required String? authorId,
    required String? title,
    String? description,
    String? context,
    List<String>? imageIds,
    double? latitude,
    double? longitude,
    DateTime? startAt,
    DateTime? endAt,
    ({String question, List<String> variants})? polling,
    Set<String>? tags,
    int? ticker = 0,
    String? iconCode,
    int? iconBackground,
    int? state,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBeacon, [], {
              #authorId: authorId,
              #title: title,
              #description: description,
              #context: context,
              #imageIds: imageIds,
              #latitude: latitude,
              #longitude: longitude,
              #startAt: startAt,
              #endAt: endAt,
              #polling: polling,
              #tags: tags,
              #ticker: ticker,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #state: state,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#createBeacon, [], {
                  #authorId: authorId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #imageIds: imageIds,
                  #latitude: latitude,
                  #longitude: longitude,
                  #startAt: startAt,
                  #endAt: endAt,
                  #polling: polling,
                  #tags: tags,
                  #ticker: ticker,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #state: state,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> getBeaconById({
    required String? beaconId,
    String? filterByUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconById, [], {
              #beaconId: beaconId,
              #filterByUserId: filterByUserId,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#getBeaconById, [], {
                  #beaconId: beaconId,
                  #filterByUserId: filterByUserId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> updateDraftBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    ({String question, List<String> variants})? polling,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraftBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #polling: polling,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateDraftBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #polling: polling,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> updateBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<void> deleteBeaconById(String? id, {required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeaconById, [id], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateBeaconState({
    required String? beaconId,
    required int? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeaconState, [], {
              #beaconId: beaconId,
              #state: state,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addImage({
    required String? beaconId,
    required String? imageId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
              #position: position,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeImage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getImageCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageCount, [beaconId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> reorderImages({
    required String? beaconId,
    required List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderImages, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.BeaconEntity> updatePublicStatus({
    required String? beaconId,
    required String? userId,
    required int? publicStatus,
    String? lastPublicMeaningfulChange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePublicStatus, [], {
              #beaconId: beaconId,
              #userId: userId,
              #publicStatus: publicStatus,
              #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updatePublicStatus, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #publicStatus: publicStatus,
                  #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);
}

/// A class which mocks [CommitmentRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommitmentRepositoryPort extends _i1.Mock
    implements _i6.CommitmentRepositoryPort {
  MockCommitmentRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> upsert({
    required String? beaconId,
    required String? userId,
    String? message = '',
    String? helpType,
    int? status = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #beaconId: beaconId,
              #userId: userId,
              #message: message,
              #helpType: helpType,
              #status: status,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> withdraw({
    required String? beaconId,
    required String? userId,
    required String? uncommitReason,
    String? message = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [], {
              #beaconId: beaconId,
              #userId: userId,
              #uncommitReason: uncommitReason,
              #message: message,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.CommitmentEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i7.CommitmentEntity>>);

  @override
  _i5.Future<List<_i7.CommitmentEntity>> fetchAllByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i7.CommitmentEntity>>);

  @override
  _i5.Future<List<_i7.CommitmentEntity>> fetchByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByUserId, [userId]),
            returnValue: _i5.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i7.CommitmentEntity>>);

  @override
  _i5.Future<bool> hasActiveCommitment({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveCommitment, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [CoordinationRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoordinationRepositoryPort extends _i1.Mock
    implements _i8.CoordinationRepositoryPort {
  MockCoordinationRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> deleteForCommit({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteForCommit, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertResponse({
    required String? beaconId,
    required String? commitUserId,
    required String? authorUserId,
    required int? responseType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertResponse, [], {
              #beaconId: beaconId,
              #commitUserId: commitUserId,
              #authorUserId: authorUserId,
              #responseType: responseType,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<({int coordinationStatus, DateTime? coordinationStatusUpdatedAt})>
  beaconCoordinationSnapshot(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#beaconCoordinationSnapshot, [beaconId]),
            returnValue:
                _i5.Future<
                  ({
                    int coordinationStatus,
                    DateTime? coordinationStatusUpdatedAt,
                  })
                >.value((
                  coordinationStatus: 0,
                  coordinationStatusUpdatedAt: null,
                )),
          )
          as _i5.Future<
            ({int coordinationStatus, DateTime? coordinationStatusUpdatedAt})
          >);

  @override
  _i5.Future<void> setBeaconCoordinationFields({
    required String? beaconId,
    required int? coordinationStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setBeaconCoordinationFields, [], {
              #beaconId: beaconId,
              #coordinationStatus: coordinationStatus,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recomputeAndPersistBeaconCoordinationStatus(
    String? beaconId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recomputeAndPersistBeaconCoordinationStatus, [
              beaconId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.CommitmentWithCoordinationRow>>
  commitmentsWithCoordination(String? beaconId, {required String? viewerId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #commitmentsWithCoordination,
              [beaconId],
              {#viewerId: viewerId},
            ),
            returnValue:
                _i5.Future<List<_i9.CommitmentWithCoordinationRow>>.value(
                  <_i9.CommitmentWithCoordinationRow>[],
                ),
          )
          as _i5.Future<List<_i9.CommitmentWithCoordinationRow>>);
}

/// A class which mocks [InboxRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepositoryPort extends _i1.Mock
    implements _i10.InboxRepositoryPort {
  MockInboxRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i11.InboxItemEntity>> fetchByUserId(
    String? userId, {
    String? context,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByUserId,
              [userId],
              {#context: context, #limit: limit, #offset: offset},
            ),
            returnValue: _i5.Future<List<_i11.InboxItemEntity>>.value(
              <_i11.InboxItemEntity>[],
            ),
          )
          as _i5.Future<List<_i11.InboxItemEntity>>);

  @override
  _i5.Future<List<String>> fetchRejectedUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRejectedUserIdsByBeacon, [beaconId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> fetchWatchingUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchingUserIdsByBeacon, [beaconId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> applyTombstoneAfterWithdraw({
    required String? userId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTombstoneAfterWithdraw, [], {
              #userId: userId,
              #beaconId: beaconId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertWatchingForSender({
    required String? senderId,
    required String? beaconId,
    String? context,
    bool? touchForwardOrdering = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWatchingForSender, [], {
              #senderId: senderId,
              #beaconId: beaconId,
              #context: context,
              #touchForwardOrdering: touchForwardOrdering,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setStatus({
    required String? userId,
    required String? beaconId,
    required int? status,
    required String? rejectionMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [], {
              #userId: userId,
              #beaconId: beaconId,
              #status: status,
              #rejectionMessage: rejectionMessage,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PersonCapabilityEventRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonCapabilityEventRepositoryPort extends _i1.Mock
    implements _i3.PersonCapabilityEventRepositoryPort {
  MockPersonCapabilityEventRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> upsertPrivateLabels({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<String>> fetchPrivateLabels({
    required String? observerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
            }),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> insertForwardReasons({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertForwardReasons, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertCommitRole({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCommitRole, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slug: slug,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertCloseAcknowledgements({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCloseAcknowledgements, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.PersonCapabilityCuesRow> fetchCues({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCues, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i5.Future<_i3.PersonCapabilityCuesRow>.value(
              _FakePersonCapabilityCuesRow_1(
                this,
                Invocation.method(#fetchCues, [], {
                  #viewerId: viewerId,
                  #subjectId: subjectId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PersonCapabilityCuesRow>);
}
