// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/contact_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/entity/user_contact_entity.dart' as _i4;
import 'package:tentura_server/domain/port/user_contact_repository_port.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserContactRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContactRepositoryPort extends _i1.Mock
    implements _i2.UserContactRepositoryPort {
  MockUserContactRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsert({
    required String? viewerId,
    required String? subjectId,
    required String? contactName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
              #contactName: contactName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> delete({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.UserContactEntity>> fetchAllByViewer({
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByViewer, [], {#viewerId: viewerId}),
            returnValue: _i3.Future<List<_i4.UserContactEntity>>.value(
              <_i4.UserContactEntity>[],
            ),
          )
          as _i3.Future<List<_i4.UserContactEntity>>);

  @override
  _i3.Future<String?> getName({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getName, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
