// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/forward_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/data/service/beacon_room_push_service.dart'
    as _i12;
import 'package:tentura_server/domain/entity/beacon_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/commitment_entity.dart' as _i9;
import 'package:tentura_server/domain/entity/forward_edge_entity.dart' as _i7;
import 'package:tentura_server/domain/entity/inbox_item_entity.dart' as _i11;
import 'package:tentura_server/domain/port/beacon_repository_port.dart' as _i4;
import 'package:tentura_server/domain/port/commitment_repository_port.dart'
    as _i8;
import 'package:tentura_server/domain/port/forward_edge_repository_port.dart'
    as _i6;
import 'package:tentura_server/domain/port/inbox_repository_port.dart' as _i10;
import 'package:tentura_server/domain/port/person_capability_event_repository_port.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBeaconEntity_0 extends _i1.SmartFake implements _i2.BeaconEntity {
  _FakeBeaconEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonCapabilityCuesRow_1 extends _i1.SmartFake
    implements _i3.PersonCapabilityCuesRow {
  _FakePersonCapabilityCuesRow_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeaconRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRepositoryPort extends _i1.Mock
    implements _i4.BeaconRepositoryPort {
  MockBeaconRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BeaconEntity> createBeacon({
    required String? authorId,
    required String? title,
    String? description,
    String? context,
    List<String>? imageIds,
    double? latitude,
    double? longitude,
    DateTime? startAt,
    DateTime? endAt,
    ({String question, List<String> variants})? polling,
    Set<String>? tags,
    int? ticker = 0,
    String? iconCode,
    int? iconBackground,
    int? state,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBeacon, [], {
              #authorId: authorId,
              #title: title,
              #description: description,
              #context: context,
              #imageIds: imageIds,
              #latitude: latitude,
              #longitude: longitude,
              #startAt: startAt,
              #endAt: endAt,
              #polling: polling,
              #tags: tags,
              #ticker: ticker,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #state: state,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#createBeacon, [], {
                  #authorId: authorId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #imageIds: imageIds,
                  #latitude: latitude,
                  #longitude: longitude,
                  #startAt: startAt,
                  #endAt: endAt,
                  #polling: polling,
                  #tags: tags,
                  #ticker: ticker,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #state: state,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> getBeaconById({
    required String? beaconId,
    String? filterByUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconById, [], {
              #beaconId: beaconId,
              #filterByUserId: filterByUserId,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#getBeaconById, [], {
                  #beaconId: beaconId,
                  #filterByUserId: filterByUserId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> updateDraftBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    ({String question, List<String> variants})? polling,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraftBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #polling: polling,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateDraftBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #polling: polling,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<_i2.BeaconEntity> updateBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);

  @override
  _i5.Future<void> deleteBeaconById(String? id, {required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeaconById, [id], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateBeaconState({
    required String? beaconId,
    required int? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeaconState, [], {
              #beaconId: beaconId,
              #state: state,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addImage({
    required String? beaconId,
    required String? imageId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
              #position: position,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeImage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getImageCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageCount, [beaconId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> reorderImages({
    required String? beaconId,
    required List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderImages, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.BeaconEntity> updatePublicStatus({
    required String? beaconId,
    required String? userId,
    required int? publicStatus,
    String? lastPublicMeaningfulChange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePublicStatus, [], {
              #beaconId: beaconId,
              #userId: userId,
              #publicStatus: publicStatus,
              #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
            }),
            returnValue: _i5.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updatePublicStatus, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #publicStatus: publicStatus,
                  #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BeaconEntity>);
}

/// A class which mocks [ForwardEdgeRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockForwardEdgeRepositoryPort extends _i1.Mock
    implements _i6.ForwardEdgeRepositoryPort {
  MockForwardEdgeRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> create({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    required String? note,
    String? context,
    String? parentEdgeId,
    String? batchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #note: note,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #batchId: batchId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createBatch({
    required String? beaconId,
    required String? senderId,
    required List<String>? recipientIds,
    required String? batchId,
    required String Function(String)? noteForRecipient,
    String? context,
    String? parentEdgeId,
    _i5.Future<void> Function()? onAfterEdgesInserted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientIds: recipientIds,
              #batchId: batchId,
              #noteForRecipient: noteForRecipient,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #onAfterEdgesInserted: onAfterEdgesInserted,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ForwardEdgeEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<_i7.ForwardEdgeEntity>>.value(
              <_i7.ForwardEdgeEntity>[],
            ),
          )
          as _i5.Future<List<_i7.ForwardEdgeEntity>>);

  @override
  _i5.Future<List<_i7.ForwardEdgeEntity>> fetchByRecipientId(
    String? recipientId, {
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByRecipientId,
              [recipientId],
              {#context: context},
            ),
            returnValue: _i5.Future<List<_i7.ForwardEdgeEntity>>.value(
              <_i7.ForwardEdgeEntity>[],
            ),
          )
          as _i5.Future<List<_i7.ForwardEdgeEntity>>);

  @override
  _i5.Future<List<String>> fetchDistinctSenderIdsByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDistinctSenderIdsByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);
}

/// A class which mocks [CommitmentRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommitmentRepositoryPort extends _i1.Mock
    implements _i8.CommitmentRepositoryPort {
  MockCommitmentRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> upsert({
    required String? beaconId,
    required String? userId,
    String? message = '',
    List<String>? helpTypes,
    int? status = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #beaconId: beaconId,
              #userId: userId,
              #message: message,
              #helpTypes: helpTypes,
              #status: status,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> withdraw({
    required String? beaconId,
    required String? userId,
    required String? uncommitReason,
    String? message = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [], {
              #beaconId: beaconId,
              #userId: userId,
              #uncommitReason: uncommitReason,
              #message: message,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.CommitmentEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<_i9.CommitmentEntity>>.value(
              <_i9.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i9.CommitmentEntity>>);

  @override
  _i5.Future<List<_i9.CommitmentEntity>> fetchAllByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i5.Future<List<_i9.CommitmentEntity>>.value(
              <_i9.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i9.CommitmentEntity>>);

  @override
  _i5.Future<List<_i9.CommitmentEntity>> fetchByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByUserId, [userId]),
            returnValue: _i5.Future<List<_i9.CommitmentEntity>>.value(
              <_i9.CommitmentEntity>[],
            ),
          )
          as _i5.Future<List<_i9.CommitmentEntity>>);

  @override
  _i5.Future<bool> hasActiveCommitment({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveCommitment, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [InboxRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepositoryPort extends _i1.Mock
    implements _i10.InboxRepositoryPort {
  MockInboxRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i11.InboxItemEntity>> fetchByUserId(
    String? userId, {
    String? context,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByUserId,
              [userId],
              {#context: context, #limit: limit, #offset: offset},
            ),
            returnValue: _i5.Future<List<_i11.InboxItemEntity>>.value(
              <_i11.InboxItemEntity>[],
            ),
          )
          as _i5.Future<List<_i11.InboxItemEntity>>);

  @override
  _i5.Future<List<String>> fetchRejectedUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRejectedUserIdsByBeacon, [beaconId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> fetchWatchingUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchingUserIdsByBeacon, [beaconId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> applyTombstoneAfterWithdraw({
    required String? userId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTombstoneAfterWithdraw, [], {
              #userId: userId,
              #beaconId: beaconId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertWatchingForSender({
    required String? senderId,
    required String? beaconId,
    String? context,
    bool? touchForwardOrdering = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWatchingForSender, [], {
              #senderId: senderId,
              #beaconId: beaconId,
              #context: context,
              #touchForwardOrdering: touchForwardOrdering,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setStatus({
    required String? userId,
    required String? beaconId,
    required int? status,
    required String? rejectionMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [], {
              #userId: userId,
              #beaconId: beaconId,
              #status: status,
              #rejectionMessage: rejectionMessage,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PersonCapabilityEventRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonCapabilityEventRepositoryPort extends _i1.Mock
    implements _i3.PersonCapabilityEventRepositoryPort {
  MockPersonCapabilityEventRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> upsertPrivateLabels({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<String>> fetchPrivateLabels({
    required String? observerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
            }),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> insertForwardReasons({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertForwardReasons, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertCommitRole({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCommitRole, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slug: slug,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertCloseAcknowledgements({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCloseAcknowledgements, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.PersonCapabilityCuesRow> fetchCues({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCues, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i5.Future<_i3.PersonCapabilityCuesRow>.value(
              _FakePersonCapabilityCuesRow_1(
                this,
                Invocation.method(#fetchCues, [], {
                  #viewerId: viewerId,
                  #subjectId: subjectId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PersonCapabilityCuesRow>);

  @override
  _i5.Future<void> insertTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ViewerVisibleCapabilityRow>>
  fetchDeduplicatedCapabilities({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeduplicatedCapabilities, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i5.Future<List<_i3.ViewerVisibleCapabilityRow>>.value(
              <_i3.ViewerVisibleCapabilityRow>[],
            ),
          )
          as _i5.Future<List<_i3.ViewerVisibleCapabilityRow>>);

  @override
  _i5.Future<List<_i3.ForwardReasonRow>> fetchForwardReasonsByBeaconId({
    required String? beaconId,
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForwardReasonsByBeaconId, [], {
              #beaconId: beaconId,
              #viewerId: viewerId,
            }),
            returnValue: _i5.Future<List<_i3.ForwardReasonRow>>.value(
              <_i3.ForwardReasonRow>[],
            ),
          )
          as _i5.Future<List<_i3.ForwardReasonRow>>);
}

/// A class which mocks [BeaconRoomPushService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRoomPushService extends _i1.Mock
    implements _i12.BeaconRoomPushService {
  MockBeaconRoomPushService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> notifyForwardReceived({
    required String? beaconId,
    required String? senderId,
    required String? beaconAuthorId,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyForwardReceived, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #beaconAuthorId: beaconAuthorId,
              #recipientIds: recipientIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyCommitToAuthor({
    required String? beaconId,
    required String? committerId,
    required String? authorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyCommitToAuthor, [], {
              #beaconId: beaconId,
              #committerId: committerId,
              #authorId: authorId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyRoomAdmitted({
    required String? receiverId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRoomAdmitted, [], {
              #receiverId: receiverId,
              #beaconId: beaconId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyNeedInfoRequested({
    required String? receiverId,
    required String? beaconId,
    required String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyNeedInfoRequested, [], {
              #receiverId: receiverId,
              #beaconId: beaconId,
              #actorUserId: actorUserId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyHelpOfferedToModerators({
    required String? beaconId,
    required String? offererUserId,
    required List<String>? moderatorUserIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHelpOfferedToModerators, [], {
              #beaconId: beaconId,
              #offererUserId: offererUserId,
              #moderatorUserIds: moderatorUserIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyPlanUpdatedToRoom({
    required String? beaconId,
    required String? actorUserId,
    required List<String>? admittedUserIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPlanUpdatedToRoom, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #admittedUserIds: admittedUserIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyBlockerRoomEvent({
    required String? beaconId,
    required String? actorUserId,
    required Set<String>? receiverIds,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBlockerRoomEvent, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #receiverIds: receiverIds,
              #body: body,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyNextMoveUpdated({
    required String? beaconId,
    required String? targetUserId,
    required String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyNextMoveUpdated, [], {
              #beaconId: beaconId,
              #targetUserId: targetUserId,
              #actorUserId: actorUserId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> notifyFactPinned({
    required String? beaconId,
    required String? actorUserId,
    required bool? isPublic,
    required List<String>? recipientUserIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyFactPinned, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #isPublic: isPublic,
              #recipientUserIds: recipientUserIds,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
