// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/forward_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/domain/entity/commitment_entity.dart' as _i7;
import 'package:tentura_server/domain/entity/forward_edge_entity.dart' as _i5;
import 'package:tentura_server/domain/entity/inbox_item_entity.dart' as _i9;
import 'package:tentura_server/domain/port/commitment_repository_port.dart'
    as _i6;
import 'package:tentura_server/domain/port/forward_edge_repository_port.dart'
    as _i3;
import 'package:tentura_server/domain/port/inbox_repository_port.dart' as _i8;
import 'package:tentura_server/domain/port/person_capability_event_repository_port.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePersonCapabilityCuesRow_0 extends _i1.SmartFake
    implements _i2.PersonCapabilityCuesRow {
  _FakePersonCapabilityCuesRow_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForwardEdgeRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockForwardEdgeRepositoryPort extends _i1.Mock
    implements _i3.ForwardEdgeRepositoryPort {
  MockForwardEdgeRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> create({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    required String? note,
    String? context,
    String? parentEdgeId,
    String? batchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #note: note,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #batchId: batchId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createBatch({
    required String? beaconId,
    required String? senderId,
    required List<String>? recipientIds,
    required String? batchId,
    required String Function(String)? noteForRecipient,
    String? context,
    String? parentEdgeId,
    _i4.Future<void> Function()? onAfterEdgesInserted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientIds: recipientIds,
              #batchId: batchId,
              #noteForRecipient: noteForRecipient,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #onAfterEdgesInserted: onAfterEdgesInserted,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ForwardEdgeEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i4.Future<List<_i5.ForwardEdgeEntity>>.value(
              <_i5.ForwardEdgeEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ForwardEdgeEntity>>);

  @override
  _i4.Future<List<_i5.ForwardEdgeEntity>> fetchByRecipientId(
    String? recipientId, {
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByRecipientId,
              [recipientId],
              {#context: context},
            ),
            returnValue: _i4.Future<List<_i5.ForwardEdgeEntity>>.value(
              <_i5.ForwardEdgeEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ForwardEdgeEntity>>);

  @override
  _i4.Future<List<String>> fetchDistinctSenderIdsByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDistinctSenderIdsByBeaconId, [beaconId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}

/// A class which mocks [CommitmentRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommitmentRepositoryPort extends _i1.Mock
    implements _i6.CommitmentRepositoryPort {
  MockCommitmentRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> upsert({
    required String? beaconId,
    required String? userId,
    String? message = '',
    String? helpType,
    int? status = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #beaconId: beaconId,
              #userId: userId,
              #message: message,
              #helpType: helpType,
              #status: status,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> withdraw({
    required String? beaconId,
    required String? userId,
    required String? uncommitReason,
    String? message = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [], {
              #beaconId: beaconId,
              #userId: userId,
              #uncommitReason: uncommitReason,
              #message: message,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.CommitmentEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i4.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i4.Future<List<_i7.CommitmentEntity>>);

  @override
  _i4.Future<List<_i7.CommitmentEntity>> fetchAllByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i4.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i4.Future<List<_i7.CommitmentEntity>>);

  @override
  _i4.Future<List<_i7.CommitmentEntity>> fetchByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByUserId, [userId]),
            returnValue: _i4.Future<List<_i7.CommitmentEntity>>.value(
              <_i7.CommitmentEntity>[],
            ),
          )
          as _i4.Future<List<_i7.CommitmentEntity>>);

  @override
  _i4.Future<bool> hasActiveCommitment({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveCommitment, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [InboxRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepositoryPort extends _i1.Mock
    implements _i8.InboxRepositoryPort {
  MockInboxRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i9.InboxItemEntity>> fetchByUserId(
    String? userId, {
    String? context,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByUserId,
              [userId],
              {#context: context, #limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<_i9.InboxItemEntity>>.value(
              <_i9.InboxItemEntity>[],
            ),
          )
          as _i4.Future<List<_i9.InboxItemEntity>>);

  @override
  _i4.Future<List<String>> fetchRejectedUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRejectedUserIdsByBeacon, [beaconId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> fetchWatchingUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchingUserIdsByBeacon, [beaconId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> applyTombstoneAfterWithdraw({
    required String? userId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTombstoneAfterWithdraw, [], {
              #userId: userId,
              #beaconId: beaconId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertWatchingForSender({
    required String? senderId,
    required String? beaconId,
    String? context,
    bool? touchForwardOrdering = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWatchingForSender, [], {
              #senderId: senderId,
              #beaconId: beaconId,
              #context: context,
              #touchForwardOrdering: touchForwardOrdering,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStatus({
    required String? userId,
    required String? beaconId,
    required int? status,
    required String? rejectionMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [], {
              #userId: userId,
              #beaconId: beaconId,
              #status: status,
              #rejectionMessage: rejectionMessage,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PersonCapabilityEventRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonCapabilityEventRepositoryPort extends _i1.Mock
    implements _i2.PersonCapabilityEventRepositoryPort {
  MockPersonCapabilityEventRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> upsertPrivateLabels({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> fetchPrivateLabels({
    required String? observerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
            }),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> insertForwardReasons({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertForwardReasons, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
              #note: note,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertCommitRole({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCommitRole, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slug: slug,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertCloseAcknowledgements({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCloseAcknowledgements, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PersonCapabilityCuesRow> fetchCues({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCues, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i4.Future<_i2.PersonCapabilityCuesRow>.value(
              _FakePersonCapabilityCuesRow_0(
                this,
                Invocation.method(#fetchCues, [], {
                  #viewerId: viewerId,
                  #subjectId: subjectId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PersonCapabilityCuesRow>);

  @override
  _i4.Future<void> insertTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ViewerVisibleCapabilityRow>>
  fetchDeduplicatedCapabilities({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeduplicatedCapabilities, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i4.Future<List<_i2.ViewerVisibleCapabilityRow>>.value(
              <_i2.ViewerVisibleCapabilityRow>[],
            ),
          )
          as _i4.Future<List<_i2.ViewerVisibleCapabilityRow>>);
}
