// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/forward_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tentura_root/domain/entity/beacon_cover_source.dart' as _i6;
import 'package:tentura_root/domain/entity/beacon_status.dart' as _i7;
import 'package:tentura_server/domain/capability/capability_evidence_models.dart'
    as _i10;
import 'package:tentura_server/domain/entity/beacon_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/beacon_media_state.dart' as _i4;
import 'package:tentura_server/domain/entity/forward_attribution_entity.dart'
    as _i13;
import 'package:tentura_server/domain/entity/forward_attribution_method.dart'
    as _i12;
import 'package:tentura_server/domain/entity/forward_edge_created.dart' as _i16;
import 'package:tentura_server/domain/entity/forward_edge_entity.dart' as _i15;
import 'package:tentura_server/domain/entity/help_offer_entity.dart' as _i18;
import 'package:tentura_server/domain/entity/inbox_item_entity.dart' as _i20;
import 'package:tentura_server/domain/port/beacon_repository_port.dart' as _i5;
import 'package:tentura_server/domain/port/capability_evidence_port.dart'
    as _i9;
import 'package:tentura_server/domain/port/forward_attribution_repository_port.dart'
    as _i11;
import 'package:tentura_server/domain/port/forward_edge_repository_port.dart'
    as _i14;
import 'package:tentura_server/domain/port/help_offer_repository_port.dart'
    as _i17;
import 'package:tentura_server/domain/port/inbox_repository_port.dart' as _i19;
import 'package:tentura_server/domain/port/person_visibility_repository_port.dart'
    as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBeaconEntity_0 extends _i1.SmartFake implements _i2.BeaconEntity {
  _FakeBeaconEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeaconMediaSnapshot_2 extends _i1.SmartFake
    implements _i4.BeaconMediaSnapshot {
  _FakeBeaconMediaSnapshot_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeaconRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRepositoryPort extends _i1.Mock
    implements _i5.BeaconRepositoryPort {
  MockBeaconRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.BeaconEntity> createBeacon({
    required String? authorId,
    required String? title,
    String? description,
    String? context,
    List<String>? imageIds,
    double? latitude,
    double? longitude,
    DateTime? startAt,
    DateTime? endAt,
    Set<String>? tags,
    Set<String>? needs,
    int? ticker = 0,
    String? primaryNeedSlug,
    String? coverImageId,
    _i6.BeaconCoverSource? coverSource = _i6.BeaconCoverSource.photo,
    _i7.BeaconStatus? status,
    String? addressLabel,
    String? lineageParentBeaconId,
    String? lineageRootBeaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBeacon, [], {
              #authorId: authorId,
              #title: title,
              #description: description,
              #context: context,
              #imageIds: imageIds,
              #latitude: latitude,
              #longitude: longitude,
              #startAt: startAt,
              #endAt: endAt,
              #tags: tags,
              #needs: needs,
              #ticker: ticker,
              #primaryNeedSlug: primaryNeedSlug,
              #coverImageId: coverImageId,
              #coverSource: coverSource,
              #status: status,
              #addressLabel: addressLabel,
              #lineageParentBeaconId: lineageParentBeaconId,
              #lineageRootBeaconId: lineageRootBeaconId,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#createBeacon, [], {
                  #authorId: authorId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #imageIds: imageIds,
                  #latitude: latitude,
                  #longitude: longitude,
                  #startAt: startAt,
                  #endAt: endAt,
                  #tags: tags,
                  #needs: needs,
                  #ticker: ticker,
                  #primaryNeedSlug: primaryNeedSlug,
                  #coverImageId: coverImageId,
                  #coverSource: coverSource,
                  #status: status,
                  #addressLabel: addressLabel,
                  #lineageParentBeaconId: lineageParentBeaconId,
                  #lineageRootBeaconId: lineageRootBeaconId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> getBeaconById({
    required String? beaconId,
    String? filterByUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconById, [], {
              #beaconId: beaconId,
              #filterByUserId: filterByUserId,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#getBeaconById, [], {
                  #beaconId: beaconId,
                  #filterByUserId: filterByUserId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> updateDraftBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? primaryNeedSlug,
    String? addressLabel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraftBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #primaryNeedSlug: primaryNeedSlug,
              #addressLabel: addressLabel,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateDraftBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #primaryNeedSlug: primaryNeedSlug,
                  #addressLabel: addressLabel,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> updateBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? primaryNeedSlug,
    String? addressLabel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #primaryNeedSlug: primaryNeedSlug,
              #addressLabel: addressLabel,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #primaryNeedSlug: primaryNeedSlug,
                  #addressLabel: addressLabel,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<void> deleteBeaconById(String? id, {required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeaconById, [id], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<T> runInBeaconStateTransaction<T>({
    required String? beaconId,
    required String? userId,
    required _i3.Future<T> Function(_i2.BeaconEntity)? fn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runInBeaconStateTransaction, [], {
              #beaconId: beaconId,
              #userId: userId,
              #fn: fn,
            }),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#runInBeaconStateTransaction, [], {
                      #beaconId: beaconId,
                      #userId: userId,
                      #fn: fn,
                    }),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#runInBeaconStateTransaction, [], {
                    #beaconId: beaconId,
                    #userId: userId,
                    #fn: fn,
                  }),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> recordBeaconStatusTransition({
    required String? beaconId,
    required _i7.BeaconStatus? fromStatus,
    required _i7.BeaconStatus? toStatus,
    required String? reason,
    required String? actorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordBeaconStatusTransition, [], {
              #beaconId: beaconId,
              #fromStatus: fromStatus,
              #toStatus: toStatus,
              #reason: reason,
              #actorId: actorId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addImage({
    required String? beaconId,
    required String? imageId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
              #position: position,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeImage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getImageCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageCount, [beaconId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countRecentByAuthor({
    required String? userId,
    required Duration? window,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countRecentByAuthor, [], {
              #userId: userId,
              #window: window,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> reorderImages({
    required String? beaconId,
    required List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderImages, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.BeaconEntity> publishDraft({
    required String? id,
    required String? actorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishDraft, [], {#id: id, #actorId: actorId}),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#publishDraft, [], {
                  #id: id,
                  #actorId: actorId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i4.BeaconMediaSnapshot> getMediaSnapshot(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaSnapshot, [beaconId]),
            returnValue: _i3.Future<_i4.BeaconMediaSnapshot>.value(
              _FakeBeaconMediaSnapshot_2(
                this,
                Invocation.method(#getMediaSnapshot, [beaconId]),
              ),
            ),
          )
          as _i3.Future<_i4.BeaconMediaSnapshot>);

  @override
  _i3.Future<void> insertStage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertStage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStage({required String? imageId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStage, [], {#imageId: imageId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> replaceMedia({
    required String? beaconId,
    required List<String>? imageIds,
    required String? coverImageId,
    required _i6.BeaconCoverSource? coverSource,
    String? coverThumbImageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceMedia, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
              #coverImageId: coverImageId,
              #coverSource: coverSource,
              #coverThumbImageId: coverThumbImageId,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> setCover({
    required String? beaconId,
    required String? coverImageId,
    required _i6.BeaconCoverSource? coverSource,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setCover, [], {
              #beaconId: beaconId,
              #coverImageId: coverImageId,
              #coverSource: coverSource,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.BeaconStageRow>> staleStages({
    required DateTime? olderThan,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#staleStages, [], {
              #olderThan: olderThan,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.BeaconStageRow>>.value(
              <_i4.BeaconStageRow>[],
            ),
          )
          as _i3.Future<List<_i4.BeaconStageRow>>);

  @override
  _i3.Future<int> reviewReopenCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#reviewReopenCount, [beaconId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> incrementReviewReopenCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementReviewReopenCount, [beaconId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CapabilityEvidencePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapabilityEvidencePort extends _i1.Mock
    implements _i9.CapabilityEvidencePort {
  MockCapabilityEvidencePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reconcileForwardReasons({
    required String? forwardEdgeId,
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reconcileForwardReasons, [], {
              #forwardEdgeId: forwardEdgeId,
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> emitOutcomeEvidenceBatch({
    required String? beaconId,
    required List<_i10.OutcomeEmission>? emissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#emitOutcomeEvidenceBatch, [], {
              #beaconId: beaconId,
              #emissions: emissions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revokeOutcomeEvidence({
    required String? beaconId,
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#revokeOutcomeEvidence, [], {
              #beaconId: beaconId,
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertSeedAttestation({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSeedAttestation, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ForwardAttributionRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockForwardAttributionRepositoryPort extends _i1.Mock
    implements _i11.ForwardAttributionRepositoryPort {
  MockForwardAttributionRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> record({
    required String? batchId,
    required Map<String, double>? weightByParentEdgeId,
    required _i12.ForwardAttributionMethod? method,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#record, [], {
              #batchId: batchId,
              #weightByParentEdgeId: weightByParentEdgeId,
              #method: method,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i13.ForwardAttributionEntity>> fetchByBatchIds(
    List<String>? batchIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBatchIds, [batchIds]),
            returnValue: _i3.Future<List<_i13.ForwardAttributionEntity>>.value(
              <_i13.ForwardAttributionEntity>[],
            ),
          )
          as _i3.Future<List<_i13.ForwardAttributionEntity>>);
}

/// A class which mocks [ForwardEdgeRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockForwardEdgeRepositoryPort extends _i1.Mock
    implements _i14.ForwardEdgeRepositoryPort {
  MockForwardEdgeRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i15.ForwardEdgeEntity?> fetchById(String? edgeId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchById, [edgeId]),
            returnValue: _i3.Future<_i15.ForwardEdgeEntity?>.value(),
          )
          as _i3.Future<_i15.ForwardEdgeEntity?>);

  @override
  _i3.Future<bool> existsWithParent(String? parentEdgeId) =>
      (super.noSuchMethod(
            Invocation.method(#existsWithParent, [parentEdgeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> cancel(String? edgeId, String? senderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [edgeId, senderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateNote(String? edgeId, String? senderId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [edgeId, senderId, note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAsRead(String? edgeId, String? recipientId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [edgeId, recipientId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> create({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    required String? note,
    String? context,
    String? parentEdgeId,
    String? batchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #note: note,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #batchId: batchId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i16.ForwardEdgeCreated>> createBatch({
    required String? beaconId,
    required String? senderId,
    required List<String>? recipientIds,
    required String? batchId,
    required String Function(String)? noteForRecipient,
    String? context,
    String? parentEdgeId,
    _i3.Future<void> Function()? onAfterEdgesInserted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientIds: recipientIds,
              #batchId: batchId,
              #noteForRecipient: noteForRecipient,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #onAfterEdgesInserted: onAfterEdgesInserted,
            }),
            returnValue: _i3.Future<List<_i16.ForwardEdgeCreated>>.value(
              <_i16.ForwardEdgeCreated>[],
            ),
          )
          as _i3.Future<List<_i16.ForwardEdgeCreated>>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> fetchHelpOffererPathChain({
    required String? beaconId,
    required String? helpOffererId,
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHelpOffererPathChain, [], {
              #beaconId: beaconId,
              #helpOffererId: helpOffererId,
              #viewerId: viewerId,
            }),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> fetchByRecipientId(
    String? recipientId, {
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByRecipientId,
              [recipientId],
              {#context: context},
            ),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<String>> fetchDistinctSenderIdsByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDistinctSenderIdsByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isDirectAuthorForward({
    required String? beaconId,
    required String? authorId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isDirectAuthorForward, [], {
              #beaconId: beaconId,
              #authorId: authorId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> fetchActiveInboundEdges({
    required String? beaconId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveInboundEdges, [], {
              #beaconId: beaconId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> lockActiveInboundEdges({
    required String? beaconId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lockActiveInboundEdges, [], {
              #beaconId: beaconId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i15.ForwardEdgeEntity>> fetchAllByBeaconId(
    String? beaconId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i15.ForwardEdgeEntity>>.value(
              <_i15.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i15.ForwardEdgeEntity>>);

  @override
  _i3.Future<int> countPriorOutgoingBatches({
    required String? beaconId,
    required String? senderId,
    required String? batchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countPriorOutgoingBatches, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #batchId: batchId,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i15.ForwardEdgeEntity?> findActiveEdge({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findActiveEdge, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<_i15.ForwardEdgeEntity?>.value(),
          )
          as _i3.Future<_i15.ForwardEdgeEntity?>);

  @override
  _i3.Future<void> createForInviteAccept({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    String? parentEdgeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createForInviteAccept, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #parentEdgeId: parentEdgeId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [HelpOfferRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockHelpOfferRepositoryPort extends _i1.Mock
    implements _i17.HelpOfferRepositoryPort {
  MockHelpOfferRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsert({
    required String? beaconId,
    required String? userId,
    String? message = '',
    List<String>? helpTypes,
    int? status = 0,
    int? offerKind = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #beaconId: beaconId,
              #userId: userId,
              #message: message,
              #helpTypes: helpTypes,
              #status: status,
              #offerKind: offerKind,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> withdraw({
    required String? beaconId,
    required String? userId,
    required String? withdrawReason,
    String? message = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [], {
              #beaconId: beaconId,
              #userId: userId,
              #withdrawReason: withdrawReason,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i18.HelpOfferEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i18.HelpOfferEntity>>.value(
              <_i18.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i18.HelpOfferEntity>>);

  @override
  _i3.Future<List<_i18.HelpOfferEntity>> fetchAllByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i18.HelpOfferEntity>>.value(
              <_i18.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i18.HelpOfferEntity>>);

  @override
  _i3.Future<List<_i18.HelpOfferEntity>> fetchByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByUserId, [userId]),
            returnValue: _i3.Future<List<_i18.HelpOfferEntity>>.value(
              <_i18.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i18.HelpOfferEntity>>);

  @override
  _i3.Future<bool> hasActiveHelpOffer({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveHelpOffer, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> fetchActiveHelpTypes({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveHelpTypes, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}

/// A class which mocks [InboxRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepositoryPort extends _i1.Mock
    implements _i19.InboxRepositoryPort {
  MockInboxRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i20.InboxItemEntity>> fetchByUserId(
    String? userId, {
    String? context,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByUserId,
              [userId],
              {#context: context, #limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<_i20.InboxItemEntity>>.value(
              <_i20.InboxItemEntity>[],
            ),
          )
          as _i3.Future<List<_i20.InboxItemEntity>>);

  @override
  _i3.Future<List<String>> fetchRejectedUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRejectedUserIdsByBeacon, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchWatchingUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchingUserIdsByBeacon, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> applyTombstoneAfterWithdraw({
    required String? userId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTombstoneAfterWithdraw, [], {
              #userId: userId,
              #beaconId: beaconId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertWatchingForSender({
    required String? senderId,
    required String? beaconId,
    String? context,
    bool? touchForwardOrdering = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWatchingForSender, [], {
              #senderId: senderId,
              #beaconId: beaconId,
              #context: context,
              #touchForwardOrdering: touchForwardOrdering,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setStatus({
    required String? userId,
    required String? beaconId,
    required int? status,
    required String? rejectionMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [], {
              #userId: userId,
              #beaconId: beaconId,
              #status: status,
              #rejectionMessage: rejectionMessage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markForwardCancelledForRecipient({
    required String? beaconId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markForwardCancelledForRecipient, [], {
              #beaconId: beaconId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PersonVisibilityRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonVisibilityRepositoryPort extends _i1.Mock
    implements _i21.PersonVisibilityRepositoryPort {
  MockPersonVisibilityRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Set<String>> mutuallyVisiblePeerIds({
    required String? viewerId,
    required Iterable<String>? peerIds,
    required String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mutuallyVisiblePeerIds, [], {
              #viewerId: viewerId,
              #peerIds: peerIds,
              #context: context,
            }),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);
}
