// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/help_offer_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tentura_root/domain/entity/beacon_status.dart' as _i6;
import 'package:tentura_server/domain/entity/beacon_activity_event_record.dart'
    as _i18;
import 'package:tentura_server/domain/entity/beacon_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/beacon_room_record.dart' as _i17;
import 'package:tentura_server/domain/entity/forward_edge_entity.dart' as _i13;
import 'package:tentura_server/domain/entity/gql_public/help_offer_with_coordination_row.dart'
    as _i11;
import 'package:tentura_server/domain/entity/help_offer_entity.dart' as _i9;
import 'package:tentura_server/domain/entity/inbox_item_entity.dart' as _i15;
import 'package:tentura_server/domain/port/beacon_repository_port.dart' as _i5;
import 'package:tentura_server/domain/port/beacon_room_notification_port.dart'
    as _i19;
import 'package:tentura_server/domain/port/beacon_room_repository_port.dart'
    as _i16;
import 'package:tentura_server/domain/port/coordination_repository_port.dart'
    as _i10;
import 'package:tentura_server/domain/port/forward_edge_repository_port.dart'
    as _i12;
import 'package:tentura_server/domain/port/help_offer_repository_port.dart'
    as _i8;
import 'package:tentura_server/domain/port/inbox_repository_port.dart' as _i14;
import 'package:tentura_server/domain/port/person_capability_event_repository_port.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBeaconEntity_0 extends _i1.SmartFake implements _i2.BeaconEntity {
  _FakeBeaconEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonCapabilityCuesRow_2 extends _i1.SmartFake
    implements _i4.PersonCapabilityCuesRow {
  _FakePersonCapabilityCuesRow_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeaconRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRepositoryPort extends _i1.Mock
    implements _i5.BeaconRepositoryPort {
  MockBeaconRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.BeaconEntity> createBeacon({
    required String? authorId,
    required String? title,
    String? description,
    String? context,
    List<String>? imageIds,
    double? latitude,
    double? longitude,
    DateTime? startAt,
    DateTime? endAt,
    Set<String>? tags,
    Set<String>? needs,
    int? ticker = 0,
    String? iconCode,
    int? iconBackground,
    _i6.BeaconStatus? status,
    String? needSummary,
    String? successCriteria,
    String? addressLabel,
    String? lineageParentBeaconId,
    String? lineageRootBeaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBeacon, [], {
              #authorId: authorId,
              #title: title,
              #description: description,
              #context: context,
              #imageIds: imageIds,
              #latitude: latitude,
              #longitude: longitude,
              #startAt: startAt,
              #endAt: endAt,
              #tags: tags,
              #needs: needs,
              #ticker: ticker,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #status: status,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
              #addressLabel: addressLabel,
              #lineageParentBeaconId: lineageParentBeaconId,
              #lineageRootBeaconId: lineageRootBeaconId,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#createBeacon, [], {
                  #authorId: authorId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #imageIds: imageIds,
                  #latitude: latitude,
                  #longitude: longitude,
                  #startAt: startAt,
                  #endAt: endAt,
                  #tags: tags,
                  #needs: needs,
                  #ticker: ticker,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #status: status,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                  #addressLabel: addressLabel,
                  #lineageParentBeaconId: lineageParentBeaconId,
                  #lineageRootBeaconId: lineageRootBeaconId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> getBeaconById({
    required String? beaconId,
    String? filterByUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconById, [], {
              #beaconId: beaconId,
              #filterByUserId: filterByUserId,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#getBeaconById, [], {
                  #beaconId: beaconId,
                  #filterByUserId: filterByUserId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> updateDraftBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
    String? addressLabel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraftBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
              #addressLabel: addressLabel,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateDraftBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                  #addressLabel: addressLabel,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<_i2.BeaconEntity> updateBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
    String? addressLabel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
              #addressLabel: addressLabel,
            }),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#updateBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                  #addressLabel: addressLabel,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);

  @override
  _i3.Future<void> deleteBeaconById(String? id, {required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeaconById, [id], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<T> runInBeaconStateTransaction<T>({
    required String? beaconId,
    required String? userId,
    required _i3.Future<T> Function(_i2.BeaconEntity)? fn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runInBeaconStateTransaction, [], {
              #beaconId: beaconId,
              #userId: userId,
              #fn: fn,
            }),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#runInBeaconStateTransaction, [], {
                      #beaconId: beaconId,
                      #userId: userId,
                      #fn: fn,
                    }),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#runInBeaconStateTransaction, [], {
                    #beaconId: beaconId,
                    #userId: userId,
                    #fn: fn,
                  }),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> recordBeaconStatusTransition({
    required String? beaconId,
    required _i6.BeaconStatus? fromStatus,
    required _i6.BeaconStatus? toStatus,
    required String? reason,
    required String? actorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordBeaconStatusTransition, [], {
              #beaconId: beaconId,
              #fromStatus: fromStatus,
              #toStatus: toStatus,
              #reason: reason,
              #actorId: actorId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addImage({
    required String? beaconId,
    required String? imageId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
              #position: position,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeImage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getImageCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageCount, [beaconId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countRecentByAuthor({
    required String? userId,
    required Duration? window,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countRecentByAuthor, [], {
              #userId: userId,
              #window: window,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> reorderImages({
    required String? beaconId,
    required List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderImages, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.BeaconEntity> publishDraft({
    required String? id,
    required String? actorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishDraft, [], {#id: id, #actorId: actorId}),
            returnValue: _i3.Future<_i2.BeaconEntity>.value(
              _FakeBeaconEntity_0(
                this,
                Invocation.method(#publishDraft, [], {
                  #id: id,
                  #actorId: actorId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BeaconEntity>);
}

/// A class which mocks [HelpOfferRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockHelpOfferRepositoryPort extends _i1.Mock
    implements _i8.HelpOfferRepositoryPort {
  MockHelpOfferRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsert({
    required String? beaconId,
    required String? userId,
    String? message = '',
    List<String>? helpTypes,
    int? status = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #beaconId: beaconId,
              #userId: userId,
              #message: message,
              #helpTypes: helpTypes,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> withdraw({
    required String? beaconId,
    required String? userId,
    required String? withdrawReason,
    String? message = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [], {
              #beaconId: beaconId,
              #userId: userId,
              #withdrawReason: withdrawReason,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.HelpOfferEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i9.HelpOfferEntity>>.value(
              <_i9.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i9.HelpOfferEntity>>);

  @override
  _i3.Future<List<_i9.HelpOfferEntity>> fetchAllByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i9.HelpOfferEntity>>.value(
              <_i9.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i9.HelpOfferEntity>>);

  @override
  _i3.Future<List<_i9.HelpOfferEntity>> fetchByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByUserId, [userId]),
            returnValue: _i3.Future<List<_i9.HelpOfferEntity>>.value(
              <_i9.HelpOfferEntity>[],
            ),
          )
          as _i3.Future<List<_i9.HelpOfferEntity>>);

  @override
  _i3.Future<bool> hasActiveHelpOffer({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveHelpOffer, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [CoordinationRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoordinationRepositoryPort extends _i1.Mock
    implements _i10.CoordinationRepositoryPort {
  MockCoordinationRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> deleteForCommit({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteForCommit, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertResponse({
    required String? beaconId,
    required String? offerUserId,
    required String? authorUserId,
    required int? responseType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertResponse, [], {
              #beaconId: beaconId,
              #offerUserId: offerUserId,
              #authorUserId: authorUserId,
              #responseType: responseType,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<({_i6.BeaconStatus status, DateTime? statusChangedAt})>
  beaconStatusSnapshot(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#beaconStatusSnapshot, [beaconId]),
            returnValue:
                _i3.Future<
                  ({_i6.BeaconStatus status, DateTime? statusChangedAt})
                >.value((status: _i6.BeaconStatus.open, statusChangedAt: null)),
          )
          as _i3.Future<
            ({_i6.BeaconStatus status, DateTime? statusChangedAt})
          >);

  @override
  _i3.Future<List<_i11.HelpOfferWithCoordinationRow>>
  helpOffersWithCoordination(String? beaconId, {required String? viewerId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #helpOffersWithCoordination,
              [beaconId],
              {#viewerId: viewerId},
            ),
            returnValue:
                _i3.Future<List<_i11.HelpOfferWithCoordinationRow>>.value(
                  <_i11.HelpOfferWithCoordinationRow>[],
                ),
          )
          as _i3.Future<List<_i11.HelpOfferWithCoordinationRow>>);

  @override
  _i3.Future<Map<String, int>> coordinationResponseTypeByOfferUserId(
    String? beaconId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinationResponseTypeByOfferUserId, [
              beaconId,
            ]),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}

/// A class which mocks [ForwardEdgeRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockForwardEdgeRepositoryPort extends _i1.Mock
    implements _i12.ForwardEdgeRepositoryPort {
  MockForwardEdgeRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i13.ForwardEdgeEntity?> fetchById(String? edgeId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchById, [edgeId]),
            returnValue: _i3.Future<_i13.ForwardEdgeEntity?>.value(),
          )
          as _i3.Future<_i13.ForwardEdgeEntity?>);

  @override
  _i3.Future<bool> existsWithParent(String? parentEdgeId) =>
      (super.noSuchMethod(
            Invocation.method(#existsWithParent, [parentEdgeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> cancel(String? edgeId, String? senderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [edgeId, senderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateNote(String? edgeId, String? senderId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [edgeId, senderId, note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAsRead(String? edgeId, String? recipientId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [edgeId, recipientId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> create({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    required String? note,
    String? context,
    String? parentEdgeId,
    String? batchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #note: note,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #batchId: batchId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> createBatch({
    required String? beaconId,
    required String? senderId,
    required List<String>? recipientIds,
    required String? batchId,
    required String Function(String)? noteForRecipient,
    String? context,
    String? parentEdgeId,
    _i3.Future<void> Function()? onAfterEdgesInserted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientIds: recipientIds,
              #batchId: batchId,
              #noteForRecipient: noteForRecipient,
              #context: context,
              #parentEdgeId: parentEdgeId,
              #onAfterEdgesInserted: onAfterEdgesInserted,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i13.ForwardEdgeEntity>> fetchByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<_i13.ForwardEdgeEntity>>.value(
              <_i13.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i13.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i13.ForwardEdgeEntity>> fetchHelpOffererPathChain({
    required String? beaconId,
    required String? helpOffererId,
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHelpOffererPathChain, [], {
              #beaconId: beaconId,
              #helpOffererId: helpOffererId,
              #viewerId: viewerId,
            }),
            returnValue: _i3.Future<List<_i13.ForwardEdgeEntity>>.value(
              <_i13.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i13.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<_i13.ForwardEdgeEntity>> fetchByRecipientId(
    String? recipientId, {
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByRecipientId,
              [recipientId],
              {#context: context},
            ),
            returnValue: _i3.Future<List<_i13.ForwardEdgeEntity>>.value(
              <_i13.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i13.ForwardEdgeEntity>>);

  @override
  _i3.Future<List<String>> fetchDistinctSenderIdsByBeaconId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDistinctSenderIdsByBeaconId, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isDirectAuthorForward({
    required String? beaconId,
    required String? authorId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isDirectAuthorForward, [], {
              #beaconId: beaconId,
              #authorId: authorId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i13.ForwardEdgeEntity>> fetchActiveInboundEdges({
    required String? beaconId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveInboundEdges, [], {
              #beaconId: beaconId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<List<_i13.ForwardEdgeEntity>>.value(
              <_i13.ForwardEdgeEntity>[],
            ),
          )
          as _i3.Future<List<_i13.ForwardEdgeEntity>>);

  @override
  _i3.Future<_i13.ForwardEdgeEntity?> findActiveEdge({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findActiveEdge, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<_i13.ForwardEdgeEntity?>.value(),
          )
          as _i3.Future<_i13.ForwardEdgeEntity?>);

  @override
  _i3.Future<void> createForInviteAccept({
    required String? beaconId,
    required String? senderId,
    required String? recipientId,
    String? parentEdgeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createForInviteAccept, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #recipientId: recipientId,
              #parentEdgeId: parentEdgeId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [InboxRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepositoryPort extends _i1.Mock
    implements _i14.InboxRepositoryPort {
  MockInboxRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i15.InboxItemEntity>> fetchByUserId(
    String? userId, {
    String? context,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchByUserId,
              [userId],
              {#context: context, #limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<_i15.InboxItemEntity>>.value(
              <_i15.InboxItemEntity>[],
            ),
          )
          as _i3.Future<List<_i15.InboxItemEntity>>);

  @override
  _i3.Future<List<String>> fetchRejectedUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRejectedUserIdsByBeacon, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchWatchingUserIdsByBeacon(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchingUserIdsByBeacon, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> applyTombstoneAfterWithdraw({
    required String? userId,
    required String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTombstoneAfterWithdraw, [], {
              #userId: userId,
              #beaconId: beaconId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertWatchingForSender({
    required String? senderId,
    required String? beaconId,
    String? context,
    bool? touchForwardOrdering = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWatchingForSender, [], {
              #senderId: senderId,
              #beaconId: beaconId,
              #context: context,
              #touchForwardOrdering: touchForwardOrdering,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setStatus({
    required String? userId,
    required String? beaconId,
    required int? status,
    required String? rejectionMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [], {
              #userId: userId,
              #beaconId: beaconId,
              #status: status,
              #rejectionMessage: rejectionMessage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markForwardCancelledForRecipient({
    required String? beaconId,
    required String? recipientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markForwardCancelledForRecipient, [], {
              #beaconId: beaconId,
              #recipientId: recipientId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PersonCapabilityEventRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonCapabilityEventRepositoryPort extends _i1.Mock
    implements _i4.PersonCapabilityEventRepositoryPort {
  MockPersonCapabilityEventRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertPrivateLabels({
    required String? observerId,
    required String? subjectId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> fetchPrivateLabels({
    required String? observerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateLabels, [], {
              #observerId: observerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> insertForwardReasons({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertForwardReasons, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
              #note: note,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertCommitRole({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCommitRole, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertCloseAcknowledgements({
    required String? observerId,
    required String? subjectId,
    required String? beaconId,
    required List<String>? slugs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCloseAcknowledgements, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #beaconId: beaconId,
              #slugs: slugs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.PersonCapabilityCuesRow> fetchCues({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCues, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<_i4.PersonCapabilityCuesRow>.value(
              _FakePersonCapabilityCuesRow_2(
                this,
                Invocation.method(#fetchCues, [], {
                  #viewerId: viewerId,
                  #subjectId: subjectId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.PersonCapabilityCuesRow>);

  @override
  _i3.Future<void> insertTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTombstone({
    required String? observerId,
    required String? subjectId,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTombstone, [], {
              #observerId: observerId,
              #subjectId: subjectId,
              #slug: slug,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.ViewerVisibleCapabilityRow>>
  fetchDeduplicatedCapabilities({
    required String? viewerId,
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeduplicatedCapabilities, [], {
              #viewerId: viewerId,
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<List<_i4.ViewerVisibleCapabilityRow>>.value(
              <_i4.ViewerVisibleCapabilityRow>[],
            ),
          )
          as _i3.Future<List<_i4.ViewerVisibleCapabilityRow>>);

  @override
  _i3.Future<Map<String, List<String>>> fetchTopCapabilitiesBatch({
    required String? viewerId,
    required List<String>? subjectIds,
    int? limit = 2,
    List<String>? prioritizeSlugs = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopCapabilitiesBatch, [], {
              #viewerId: viewerId,
              #subjectIds: subjectIds,
              #limit: limit,
              #prioritizeSlugs: prioritizeSlugs,
            }),
            returnValue: _i3.Future<Map<String, List<String>>>.value(
              <String, List<String>>{},
            ),
          )
          as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<List<_i4.ForwardReasonRow>> fetchForwardReasonsByBeaconId({
    required String? beaconId,
    required String? viewerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForwardReasonsByBeaconId, [], {
              #beaconId: beaconId,
              #viewerId: viewerId,
            }),
            returnValue: _i3.Future<List<_i4.ForwardReasonRow>>.value(
              <_i4.ForwardReasonRow>[],
            ),
          )
          as _i3.Future<List<_i4.ForwardReasonRow>>);

  @override
  _i3.Future<List<_i4.FriendContextRow>> fetchFriendContextsBatch({
    required String? viewerId,
    required List<String>? friendIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFriendContextsBatch, [], {
              #viewerId: viewerId,
              #friendIds: friendIds,
            }),
            returnValue: _i3.Future<List<_i4.FriendContextRow>>.value(
              <_i4.FriendContextRow>[],
            ),
          )
          as _i3.Future<List<_i4.FriendContextRow>>);
}

/// A class which mocks [BeaconRoomRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRoomRepositoryPort extends _i1.Mock
    implements _i16.BeaconRoomRepositoryPort {
  MockBeaconRoomRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> admitParticipant({
    required String? beaconId,
    required String? participantUserId,
    required String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#admitParticipant, [], {
              #beaconId: beaconId,
              #participantUserId: participantUserId,
              #actorUserId: actorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> attachmentsJsonByMessageIds(
    Iterable<String>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#attachmentsJsonByMessageIds, [messageIds]),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<String?> beaconAuthorUserId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#beaconAuthorUserId, [beaconId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int> countAttachmentsForMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#countAttachmentsForMessage, [messageId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countRoomMessagesAfter({
    required String? beaconId,
    DateTime? after,
    String? excludeAuthorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countRoomMessagesAfter, [], {
              #beaconId: beaconId,
              #after: after,
              #excludeAuthorId: excludeAuthorId,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countRecentMessagesByAuthor({
    required String? authorId,
    required Duration? window,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countRecentMessagesByAuthor, [], {
              #authorId: authorId,
              #window: window,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteRoomMessage({required String? messageId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoomMessage, [], {#messageId: messageId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i17.BeaconParticipantRecord?> findParticipant({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findParticipant, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<_i17.BeaconParticipantRecord?>.value(),
          )
          as _i3.Future<_i17.BeaconParticipantRecord?>);

  @override
  _i3.Future<_i17.BeaconRoomStateRecord?> getBeaconRoomState(
    String? beaconId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconRoomState, [beaconId]),
            returnValue: _i3.Future<_i17.BeaconRoomStateRecord?>.value(),
          )
          as _i3.Future<_i17.BeaconRoomStateRecord?>);

  @override
  _i3.Future<DateTime?> getMainRoomLastSeen({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMainRoomLastSeen, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<_i17.BeaconRoomMessageAttachmentRecord?>
  getRoomMessageAttachmentById(String? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomMessageAttachmentById, [attachmentId]),
            returnValue:
                _i3.Future<_i17.BeaconRoomMessageAttachmentRecord?>.value(),
          )
          as _i3.Future<_i17.BeaconRoomMessageAttachmentRecord?>);

  @override
  _i3.Future<_i17.BeaconRoomMessageRecord?> getRoomMessageById(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomMessageById, [messageId]),
            returnValue: _i3.Future<_i17.BeaconRoomMessageRecord?>.value(),
          )
          as _i3.Future<_i17.BeaconRoomMessageRecord?>);

  @override
  _i3.Future<Map<String, String?>> helpTypesByUserId(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#helpTypesByUserId, [beaconId]),
            returnValue: _i3.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<void> insertActivityEvent({
    required String? beaconId,
    required int? visibility,
    required int? type,
    required String? actorId,
    String? targetUserId,
    String? sourceMessageId,
    Map<String, Object?>? diff,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertActivityEvent, [], {
              #beaconId: beaconId,
              #visibility: visibility,
              #type: type,
              #actorId: actorId,
              #targetUserId: targetUserId,
              #sourceMessageId: sourceMessageId,
              #diff: diff,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, Object?>> insertAndEnrichPollMessage({
    required String? beaconId,
    required String? authorId,
    required String? linkedPollingId,
    required String? viewerUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertAndEnrichPollMessage, [], {
              #beaconId: beaconId,
              #authorId: authorId,
              #linkedPollingId: linkedPollingId,
              #viewerUserId: viewerUserId,
            }),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<_i17.BeaconRoomMessageRecord> insertRoomMessage({
    required String? beaconId,
    required String? authorId,
    required String? body,
    String? replyToMessageId,
    String? threadItemId,
    String? linkedParticipantId,
    String? linkedPollingId,
    int? semanticMarker,
    Map<String, Object?>? systemPayload,
    List<String>? mentions = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertRoomMessage, [], {
              #beaconId: beaconId,
              #authorId: authorId,
              #body: body,
              #replyToMessageId: replyToMessageId,
              #threadItemId: threadItemId,
              #linkedParticipantId: linkedParticipantId,
              #linkedPollingId: linkedPollingId,
              #semanticMarker: semanticMarker,
              #systemPayload: systemPayload,
              #mentions: mentions,
            }),
            returnValue: _i3.Future<_i17.BeaconRoomMessageRecord>.value(
              _i7.dummyValue<_i17.BeaconRoomMessageRecord>(
                this,
                Invocation.method(#insertRoomMessage, [], {
                  #beaconId: beaconId,
                  #authorId: authorId,
                  #body: body,
                  #replyToMessageId: replyToMessageId,
                  #threadItemId: threadItemId,
                  #linkedParticipantId: linkedParticipantId,
                  #linkedPollingId: linkedPollingId,
                  #semanticMarker: semanticMarker,
                  #systemPayload: systemPayload,
                  #mentions: mentions,
                }),
              ),
            ),
          )
          as _i3.Future<_i17.BeaconRoomMessageRecord>);

  @override
  _i3.Future<void> insertRoomMessageAttachmentFile({
    required String? attachmentId,
    required String? messageId,
    required int? position,
    required String? storagePath,
    required String? mime,
    required int? sizeBytes,
    required String? displayName,
    required String? mutatingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertRoomMessageAttachmentFile, [], {
              #attachmentId: attachmentId,
              #messageId: messageId,
              #position: position,
              #storagePath: storagePath,
              #mime: mime,
              #sizeBytes: sizeBytes,
              #displayName: displayName,
              #mutatingUserId: mutatingUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertRoomMessageAttachmentImage({
    required String? attachmentId,
    required String? messageId,
    required int? position,
    required String? imageId,
    required String? mime,
    required int? sizeBytes,
    required String? displayName,
    required String? mutatingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertRoomMessageAttachmentImage, [], {
              #attachmentId: attachmentId,
              #messageId: messageId,
              #position: position,
              #imageId: imageId,
              #mime: mime,
              #sizeBytes: sizeBytes,
              #displayName: displayName,
              #mutatingUserId: mutatingUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> inviteOfferUserToBeaconRoom({
    required String? beaconId,
    required String? offerUserId,
    required String? authorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#inviteOfferUserToBeaconRoom, [], {
              #beaconId: beaconId,
              #offerUserId: offerUserId,
              #authorUserId: authorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBeaconAuthor({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isBeaconAuthor, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isBeaconSteward({
    required String? beaconId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isBeaconSteward, [], {
              #beaconId: beaconId,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i18.MyWorkLastActivityEventRow>>
  latestActivityEventsByBeaconIds({
    required List<String>? beaconIds,
    required String? viewerUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#latestActivityEventsByBeaconIds, [], {
              #beaconIds: beaconIds,
              #viewerUserId: viewerUserId,
            }),
            returnValue:
                _i3.Future<List<_i18.MyWorkLastActivityEventRow>>.value(
                  <_i18.MyWorkLastActivityEventRow>[],
                ),
          )
          as _i3.Future<List<_i18.MyWorkLastActivityEventRow>>);

  @override
  _i3.Future<DateTime?> latestMainRoomMessageCreatedAt(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#latestMainRoomMessageCreatedAt, [beaconId]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<List<Map<String, Object?>>> listActivityEvents({
    required String? beaconId,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listActivityEvents, [], {
              #beaconId: beaconId,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<List<String>> listAdmittedUserIds(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#listAdmittedUserIds, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<Map<String, Object?>>> listMessagesEnriched({
    required String? beaconId,
    required String? viewerUserId,
    String? threadItemId,
    DateTime? before,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listMessagesEnriched, [], {
              #beaconId: beaconId,
              #viewerUserId: viewerUserId,
              #threadItemId: threadItemId,
              #before: before,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<List<_i17.BeaconParticipantRecord>> listParticipants(
    String? beaconId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listParticipants, [beaconId]),
            returnValue: _i3.Future<List<_i17.BeaconParticipantRecord>>.value(
              <_i17.BeaconParticipantRecord>[],
            ),
          )
          as _i3.Future<List<_i17.BeaconParticipantRecord>>);

  @override
  _i3.Future<List<String>> listStewardUserIds(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#listStewardUserIds, [beaconId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, DateTime>> mainRoomLastSeenByUserIds({
    required String? beaconId,
    required List<String>? userIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mainRoomLastSeenByUserIds, [], {
              #beaconId: beaconId,
              #userIds: userIds,
            }),
            returnValue: _i3.Future<Map<String, DateTime>>.value(
              <String, DateTime>{},
            ),
          )
          as _i3.Future<Map<String, DateTime>>);

  @override
  _i3.Future<void> markBeaconRoomSeen({
    required String? userId,
    required String? beaconId,
    required String? threadItemId,
    required DateTime? at,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markBeaconRoomSeen, [], {
              #userId: userId,
              #beaconId: beaconId,
              #threadItemId: threadItemId,
              #at: at,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markRoomMessageSemanticDone({
    required String? messageId,
    required String? actingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomMessageSemanticDone, [], {
              #messageId: messageId,
              #actingUserId: actingUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> participantOfferHelp({
    required String? beaconId,
    required String? userId,
    required String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#participantOfferHelp, [], {
              #beaconId: beaconId,
              #userId: userId,
              #note: note,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> resolveMentionUserIdsForBeacon({
    required String? beaconId,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveMentionUserIdsForBeacon, [], {
              #beaconId: beaconId,
              #body: body,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> revokeOfferUserBeaconRoomAccess({
    required String? beaconId,
    required String? offerUserId,
    required String? authorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#revokeOfferUserBeaconRoomAccess, [], {
              #beaconId: beaconId,
              #offerUserId: offerUserId,
              #authorUserId: authorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setBeaconSteward({
    required String? beaconId,
    required String? stewardUserId,
    required String? authorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setBeaconSteward, [], {
              #beaconId: beaconId,
              #stewardUserId: stewardUserId,
              #authorUserId: authorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMessage({
    required String? messageId,
    required String? newBody,
    required List<String>? mentions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [], {
              #messageId: messageId,
              #newBody: newBody,
              #mentions: mentions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> userHandlesByIds(Iterable<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#userHandlesByIds, [userIds]),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<
    Map<
      String,
      ({
        String blurHash,
        bool hasPicture,
        String imageId,
        int picHeight,
        int picWidth,
      })
    >
  >
  userPicMetaByIds(Iterable<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#userPicMetaByIds, [userIds]),
            returnValue:
                _i3.Future<
                  Map<
                    String,
                    ({
                      String blurHash,
                      bool hasPicture,
                      String imageId,
                      int picHeight,
                      int picWidth,
                    })
                  >
                >.value(
                  <
                    String,
                    ({
                      String blurHash,
                      bool hasPicture,
                      String imageId,
                      int picHeight,
                      int picWidth,
                    })
                  >{},
                ),
          )
          as _i3.Future<
            Map<
              String,
              ({
                String blurHash,
                bool hasPicture,
                String imageId,
                int picHeight,
                int picWidth,
              })
            >
          >);

  @override
  _i3.Future<Map<String, String>> userTitlesByIds(Iterable<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#userTitlesByIds, [userIds]),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);
}

/// A class which mocks [BeaconRoomNotificationPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRoomNotificationPort extends _i1.Mock
    implements _i19.BeaconRoomNotificationPort {
  MockBeaconRoomNotificationPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> notifyBlockerOpened({
    required String? beaconId,
    required String? actorUserId,
    required String? excerpt,
    String? targetPersonId,
    String? coordinationItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBlockerOpened, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #excerpt: excerpt,
              #targetPersonId: targetPersonId,
              #coordinationItemId: coordinationItemId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyBlockerResolved({
    required String? beaconId,
    required String? actorUserId,
    required String? excerpt,
    String? targetPersonId,
    String? coordinationItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBlockerResolved, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #excerpt: excerpt,
              #targetPersonId: targetPersonId,
              #coordinationItemId: coordinationItemId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyForwardReceived({
    required String? beaconId,
    required String? senderId,
    required String? beaconAuthorId,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyForwardReceived, [], {
              #beaconId: beaconId,
              #senderId: senderId,
              #beaconAuthorId: beaconAuthorId,
              #recipientIds: recipientIds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyHelpOfferToAuthor({
    required String? beaconId,
    required String? helpOffererId,
    required String? authorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHelpOfferToAuthor, [], {
              #beaconId: beaconId,
              #helpOffererId: helpOffererId,
              #authorId: authorId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyHelpOfferedToModerators({
    required String? beaconId,
    required String? offererUserId,
    required List<String>? moderatorUserIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHelpOfferedToModerators, [], {
              #beaconId: beaconId,
              #offererUserId: offererUserId,
              #moderatorUserIds: moderatorUserIds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyHelpWithdrawn({
    required String? beaconId,
    required String? withdrawerUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHelpWithdrawn, [], {
              #beaconId: beaconId,
              #withdrawerUserId: withdrawerUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyNeedsMe({
    required String? beaconId,
    required String? actorUserId,
    required String? targetUserId,
    required String? excerpt,
    String? coordinationItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyNeedsMe, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #targetUserId: targetUserId,
              #excerpt: excerpt,
              #coordinationItemId: coordinationItemId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPlanUpdatedToRoom({
    required String? beaconId,
    required String? actorUserId,
    required List<String>? admittedUserIds,
    String? planExcerpt = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPlanUpdatedToRoom, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #admittedUserIds: admittedUserIds,
              #planExcerpt: planExcerpt,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPromiseMade({
    required String? beaconId,
    required String? actorUserId,
    required String? excerpt,
    String? targetPersonId,
    String? coordinationItemId,
    bool? withdrawn = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPromiseMade, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #excerpt: excerpt,
              #targetPersonId: targetPersonId,
              #coordinationItemId: coordinationItemId,
              #withdrawn: withdrawn,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyReviewOpened({
    required String? beaconId,
    required String? beaconTitle,
    required Set<String>? recipientUserIds,
    required String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyReviewOpened, [], {
              #beaconId: beaconId,
              #beaconTitle: beaconTitle,
              #recipientUserIds: recipientUserIds,
              #actorUserId: actorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyRoomAdmitted({
    required String? receiverId,
    required String? beaconId,
    required String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRoomAdmitted, [], {
              #receiverId: receiverId,
              #beaconId: beaconId,
              #actorUserId: actorUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyStaleRemind({
    required String? beaconId,
    required String? actorUserId,
    required String? targetPersonId,
    required String? excerpt,
    String? coordinationItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyStaleRemind, [], {
              #beaconId: beaconId,
              #actorUserId: actorUserId,
              #targetPersonId: targetPersonId,
              #excerpt: excerpt,
              #coordinationItemId: coordinationItemId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
