// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/invitation_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tentura_server/data/repository/vote_user_friendship_lookup.dart'
    as _i9;
import 'package:tentura_server/domain/entity/beacon_entity.dart' as _i4;
import 'package:tentura_server/domain/entity/invitation_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/user_entity.dart' as _i3;
import 'package:tentura_server/domain/port/beacon_repository_port.dart' as _i8;
import 'package:tentura_server/domain/port/invitation_repository_port.dart'
    as _i5;
import 'package:tentura_server/domain/port/user_repository_port.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInvitationEntity_0 extends _i1.SmartFake
    implements _i2.InvitationEntity {
  _FakeInvitationEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeaconEntity_2 extends _i1.SmartFake implements _i4.BeaconEntity {
  _FakeBeaconEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InvitationRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationRepositoryPort extends _i1.Mock
    implements _i5.InvitationRepositoryPort {
  MockInvitationRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.InvitationEntity?> getById({required String? invitationId}) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [], {#invitationId: invitationId}),
            returnValue: _i6.Future<_i2.InvitationEntity?>.value(),
          )
          as _i6.Future<_i2.InvitationEntity?>);

  @override
  _i6.Future<_i2.InvitationEntity> create({
    required String? issuerId,
    String? beaconId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #issuerId: issuerId,
              #beaconId: beaconId,
            }),
            returnValue: _i6.Future<_i2.InvitationEntity>.value(
              _FakeInvitationEntity_0(
                this,
                Invocation.method(#create, [], {
                  #issuerId: issuerId,
                  #beaconId: beaconId,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.InvitationEntity>);

  @override
  _i6.Future<bool> deleteById({
    required String? invitationId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {
              #invitationId: invitationId,
              #userId: userId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [UserRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepositoryPort extends _i1.Mock
    implements _i7.UserRepositoryPort {
  MockUserRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.UserEntity> create({
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i6.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#create, [], {
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.UserEntity>);

  @override
  _i6.Future<_i3.UserEntity> createInvited({
    required String? invitationId,
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvited, [], {
              #invitationId: invitationId,
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i6.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#createInvited, [], {
                  #invitationId: invitationId,
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.UserEntity>);

  @override
  _i6.Future<_i3.UserEntity> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i6.Future<_i3.UserEntity>);

  @override
  _i6.Future<_i3.UserEntity> getByPublicKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getByPublicKey, [publicKey]),
            returnValue: _i6.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#getByPublicKey, [publicKey]),
              ),
            ),
          )
          as _i6.Future<_i3.UserEntity>);

  @override
  _i6.Future<_i3.UserEntity> getByCredential({
    required String? type,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByCredential, [], {
              #type: type,
              #identifier: identifier,
            }),
            returnValue: _i6.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#getByCredential, [], {
                  #type: type,
                  #identifier: identifier,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.UserEntity>);

  @override
  _i6.Future<void> update({
    required String? id,
    String? displayName,
    String? description,
    String? imageId,
    bool? dropImage = false,
    bool? setHandle = false,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #displayName: displayName,
              #description: description,
              #imageId: imageId,
              #dropImage: dropImage,
              #setHandle: setHandle,
              #handle: handle,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteById({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {#id: id}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> bindMutual({
    required String? invitationId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bindMutual, [], {
              #invitationId: invitationId,
              #userId: userId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [BeaconRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRepositoryPort extends _i1.Mock
    implements _i8.BeaconRepositoryPort {
  MockBeaconRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.BeaconEntity> createBeacon({
    required String? authorId,
    required String? title,
    String? description,
    String? context,
    List<String>? imageIds,
    double? latitude,
    double? longitude,
    DateTime? startAt,
    DateTime? endAt,
    Set<String>? tags,
    Set<String>? needs,
    int? ticker = 0,
    String? iconCode,
    int? iconBackground,
    int? state,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBeacon, [], {
              #authorId: authorId,
              #title: title,
              #description: description,
              #context: context,
              #imageIds: imageIds,
              #latitude: latitude,
              #longitude: longitude,
              #startAt: startAt,
              #endAt: endAt,
              #tags: tags,
              #needs: needs,
              #ticker: ticker,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #state: state,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i6.Future<_i4.BeaconEntity>.value(
              _FakeBeaconEntity_2(
                this,
                Invocation.method(#createBeacon, [], {
                  #authorId: authorId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #imageIds: imageIds,
                  #latitude: latitude,
                  #longitude: longitude,
                  #startAt: startAt,
                  #endAt: endAt,
                  #tags: tags,
                  #needs: needs,
                  #ticker: ticker,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #state: state,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BeaconEntity>);

  @override
  _i6.Future<_i4.BeaconEntity> getBeaconById({
    required String? beaconId,
    String? filterByUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBeaconById, [], {
              #beaconId: beaconId,
              #filterByUserId: filterByUserId,
            }),
            returnValue: _i6.Future<_i4.BeaconEntity>.value(
              _FakeBeaconEntity_2(
                this,
                Invocation.method(#getBeaconById, [], {
                  #beaconId: beaconId,
                  #filterByUserId: filterByUserId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BeaconEntity>);

  @override
  _i6.Future<_i4.BeaconEntity> updateDraftBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraftBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i6.Future<_i4.BeaconEntity>.value(
              _FakeBeaconEntity_2(
                this,
                Invocation.method(#updateDraftBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BeaconEntity>);

  @override
  _i6.Future<_i4.BeaconEntity> updateBeacon({
    required String? beaconId,
    required String? userId,
    required String? title,
    required String? description,
    String? context,
    Set<String>? tags,
    Set<String>? needs,
    DateTime? startAt,
    DateTime? endAt,
    double? latitude,
    double? longitude,
    String? iconCode,
    int? iconBackground,
    String? needSummary,
    String? successCriteria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeacon, [], {
              #beaconId: beaconId,
              #userId: userId,
              #title: title,
              #description: description,
              #context: context,
              #tags: tags,
              #needs: needs,
              #startAt: startAt,
              #endAt: endAt,
              #latitude: latitude,
              #longitude: longitude,
              #iconCode: iconCode,
              #iconBackground: iconBackground,
              #needSummary: needSummary,
              #successCriteria: successCriteria,
            }),
            returnValue: _i6.Future<_i4.BeaconEntity>.value(
              _FakeBeaconEntity_2(
                this,
                Invocation.method(#updateBeacon, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #title: title,
                  #description: description,
                  #context: context,
                  #tags: tags,
                  #needs: needs,
                  #startAt: startAt,
                  #endAt: endAt,
                  #latitude: latitude,
                  #longitude: longitude,
                  #iconCode: iconCode,
                  #iconBackground: iconBackground,
                  #needSummary: needSummary,
                  #successCriteria: successCriteria,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BeaconEntity>);

  @override
  _i6.Future<void> deleteBeaconById(String? id, {required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeaconById, [id], {#userId: userId}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateBeaconState({
    required String? beaconId,
    required int? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeaconState, [], {
              #beaconId: beaconId,
              #state: state,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addImage({
    required String? beaconId,
    required String? imageId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
              #position: position,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeImage({
    required String? beaconId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [], {
              #beaconId: beaconId,
              #imageId: imageId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getImageCount(String? beaconId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageCount, [beaconId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> reorderImages({
    required String? beaconId,
    required List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderImages, [], {
              #beaconId: beaconId,
              #imageIds: imageIds,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.BeaconEntity> updatePublicStatus({
    required String? beaconId,
    required String? userId,
    required int? publicStatus,
    String? lastPublicMeaningfulChange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePublicStatus, [], {
              #beaconId: beaconId,
              #userId: userId,
              #publicStatus: publicStatus,
              #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
            }),
            returnValue: _i6.Future<_i4.BeaconEntity>.value(
              _FakeBeaconEntity_2(
                this,
                Invocation.method(#updatePublicStatus, [], {
                  #beaconId: beaconId,
                  #userId: userId,
                  #publicStatus: publicStatus,
                  #lastPublicMeaningfulChange: lastPublicMeaningfulChange,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BeaconEntity>);
}

/// A class which mocks [VoteUserFriendshipLookup].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteUserFriendshipLookup extends _i1.Mock
    implements _i9.VoteUserFriendshipLookup {
  MockVoteUserFriendshipLookup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<Set<String>> reciprocalPositivePeerIds({
    required String? viewerId,
    required Iterable<String>? peerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reciprocalPositivePeerIds, [], {
              #viewerId: viewerId,
              #peerIds: peerIds,
            }),
            returnValue: _i6.Future<Set<String>>.value(<String>{}),
          )
          as _i6.Future<Set<String>>);

  @override
  _i6.Future<bool> isReciprocalSubscribe({
    required String? viewerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isReciprocalSubscribe, [], {
              #viewerId: viewerId,
              #peerId: peerId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isSubscribedTo({
    required String? viewerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribedTo, [], {
              #viewerId: viewerId,
              #peerId: peerId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
