// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/polling_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tentura_server/domain/entity/beacon_room_record.dart' as _i5;
import 'package:tentura_server/domain/port/polling_act_repository_port.dart'
    as _i2;
import 'package:tentura_server/domain/port/polling_repository_port.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PollingActRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPollingActRepositoryPort extends _i1.Mock
    implements _i2.PollingActRepositoryPort {
  MockPollingActRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsert({
    required String? authorId,
    required String? pollingId,
    required List<String>? variantIds,
    required String? pollType,
    required bool? allowRevote,
    int? score,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [], {
              #authorId: authorId,
              #pollingId: pollingId,
              #variantIds: variantIds,
              #pollType: pollType,
              #allowRevote: allowRevote,
              #score: score,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PollingRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockPollingRepositoryPort extends _i1.Mock
    implements _i4.PollingRepositoryPort {
  MockPollingRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.PollingVotePolicy?> findById(String? pollingId) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [pollingId]),
            returnValue: _i3.Future<_i5.PollingVotePolicy?>.value(),
          )
          as _i3.Future<_i5.PollingVotePolicy?>);

  @override
  _i3.Future<String> createWithVariants({
    required String? authorId,
    required String? question,
    required List<String>? variants,
    String? pollType = 'single',
    bool? isAnonymous = true,
    bool? allowRevote = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWithVariants, [], {
              #authorId: authorId,
              #question: question,
              #variants: variants,
              #pollType: pollType,
              #isAnonymous: isAnonymous,
              #allowRevote: allowRevote,
            }),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createWithVariants, [], {
                  #authorId: authorId,
                  #question: question,
                  #variants: variants,
                  #pollType: pollType,
                  #isAnonymous: isAnonymous,
                  #allowRevote: allowRevote,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}
