// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/domain/use_case/user_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tentura_server/domain/entity/account_credential_entity.dart'
    as _i3;
import 'package:tentura_server/domain/entity/asserted_contact.dart' as _i6;
import 'package:tentura_server/domain/entity/task_entity.dart' as _i11;
import 'package:tentura_server/domain/entity/user_entity.dart' as _i2;
import 'package:tentura_server/domain/port/image_repository_port.dart' as _i8;
import 'package:tentura_server/domain/port/task_repository_port.dart' as _i10;
import 'package:tentura_server/domain/port/user_repository_port.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountCredentialEntity_1 extends _i1.SmartFake
    implements _i3.AccountCredentialEntity {
  _FakeAccountCredentialEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepositoryPort extends _i1.Mock
    implements _i4.UserRepositoryPort {
  MockUserRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserEntity> create({
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#create, [], {
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> createInvited({
    required String? invitationId,
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvited, [], {
              #invitationId: invitationId,
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvited, [], {
                  #invitationId: invitationId,
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> createWithCredential({
    required _i3.CredentialType? type,
    required String? identifier,
    required String? displayName,
    String? handle,
    Map<String, Object?>? publicData,
    List<_i6.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWithCredential, [], {
              #type: type,
              #identifier: identifier,
              #displayName: displayName,
              #handle: handle,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createWithCredential, [], {
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> createInvitedWithCredential({
    required String? invitationId,
    required _i3.CredentialType? type,
    required String? identifier,
    required String? displayName,
    String? handle,
    Map<String, Object?>? publicData,
    List<_i6.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvitedWithCredential, [], {
              #invitationId: invitationId,
              #type: type,
              #identifier: identifier,
              #displayName: displayName,
              #handle: handle,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvitedWithCredential, [], {
                  #invitationId: invitationId,
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> getByPublicKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getByPublicKey, [publicKey]),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByPublicKey, [publicKey]),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> getByCredential({
    required String? type,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByCredential, [], {
              #type: type,
              #identifier: identifier,
            }),
            returnValue: _i5.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByCredential, [], {
                  #type: type,
                  #identifier: identifier,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<List<_i3.AccountCredentialEntity>> listCredentials({
    required String? accountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listCredentials, [], {#accountId: accountId}),
            returnValue: _i5.Future<List<_i3.AccountCredentialEntity>>.value(
              <_i3.AccountCredentialEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AccountCredentialEntity>>);

  @override
  _i5.Future<_i3.AccountCredentialEntity> addCredential({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCredential, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
            }),
            returnValue: _i5.Future<_i3.AccountCredentialEntity>.value(
              _FakeAccountCredentialEntity_1(
                this,
                Invocation.method(#addCredential, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AccountCredentialEntity>);

  @override
  _i5.Future<void> removeCredential({
    required String? accountId,
    required String? credentialId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeCredential, [], {
              #accountId: accountId,
              #credentialId: credentialId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> linkCredentialWithContacts({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
    List<_i6.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkCredentialWithContacts, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#linkCredentialWithContacts, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.AccountCredentialEntity> linkCredentialToAccountStrict({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
    List<_i6.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkCredentialToAccountStrict, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i5.Future<_i3.AccountCredentialEntity>.value(
              _FakeAccountCredentialEntity_1(
                this,
                Invocation.method(#linkCredentialToAccountStrict, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AccountCredentialEntity>);

  @override
  _i5.Future<String?> findCredentialId({
    required _i3.CredentialType? type,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findCredentialId, [], {
              #type: type,
              #identifier: identifier,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> addVerifiedContacts({
    required String? accountId,
    required _i3.CredentialType? source,
    List<_i6.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addVerifiedContacts, [], {
              #accountId: accountId,
              #source: source,
              #contacts: contacts,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update({
    required String? id,
    String? displayName,
    String? description,
    String? imageId,
    bool? dropImage = false,
    bool? setHandle = false,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #displayName: displayName,
              #description: description,
              #imageId: imageId,
              #dropImage: dropImage,
              #setHandle: setHandle,
              #handle: handle,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteById({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {#id: id}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> bindMutual({
    required String? invitationId,
    required String? userId,
    bool? bindFriendship = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bindMutual, [], {
              #invitationId: invitationId,
              #userId: userId,
              #bindFriendship: bindFriendship,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [ImageRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageRepositoryPort extends _i1.Mock
    implements _i8.ImageRepositoryPort {
  MockImageRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.Uint8List> get({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {#id: id}),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<String> put({
    required String? authorId,
    required _i5.Stream<_i9.Uint8List>? bytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [], {#authorId: authorId, #bytes: bytes}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#put, [], {
                  #authorId: authorId,
                  #bytes: bytes,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> update({
    required String? id,
    required String? blurHash,
    required int? height,
    required int? width,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #blurHash: blurHash,
              #height: height,
              #width: width,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete({
    required String? authorId,
    required String? imageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #authorId: authorId,
              #imageId: imageId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllOf({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllOf, [], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TaskRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepositoryPort extends _i1.Mock
    implements _i10.TaskRepositoryPort {
  MockTaskRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<T?> acquire<T extends _i11.TaskEntity<_i11.TaskDetails>>() =>
      (super.noSuchMethod(
            Invocation.method(#acquire, []),
            returnValue: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<String> schedule(_i11.TaskEntity<_i11.TaskDetails>? task) =>
      (super.noSuchMethod(
            Invocation.method(#schedule, [task]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#schedule, [task]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> complete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#complete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fail, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
