services:
  openresty:
    restart: no
    image: vbulavintsev/openresty-tentura:v0.0.12
    volumes:
      - ./openresty/conf:/etc/nginx:ro
      - ./openresty/app:/usr/local/openresty/site/lualib/app:ro
      - ./openresty/test:/usr/local/openresty/site/lualib/test:ro
      - ../tentura/build/web:/usr/local/openresty/nginx/html:ro
    environment:
      - "WORKERS=2"
      - "LUA_CODE_CACHE=off"
      - "TEST_LOCATION=test"
      - "ERROR_LOG_LEVEL=debug"

  hasura:
    restart: no
    networks:
      - proxy
    ports:
      - 8080:8080/tcp
    environment:
      - "HASURA_GRAPHQL_DEV_MODE=true"
      - "HASURA_GRAPHQL_LOG_LEVEL=debug"
      - "HASURA_GRAPHQL_ENABLE_CONSOLE=true"
      - "HASURA_GRAPHQL_ENABLE_METADATA_QUERY_LOGGING=true"
      - "HASURA_GRAPHQL_CORS_DOMAIN=https://dev.tentura.io,http://localhost:8888"

  postgres:
    restart: no
    image: vbulavintsev/postgres-tentura:v0.3.24
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - proxy
    ports:
      - 5432:5432/tcp

  meritrank-service:
    restart: no
    image: vbulavintsev/meritrank-service:v0.2.35
    networks:
      - proxy
    ports:
      - 10234:10234/tcp

  tentura:
    restart: no
    image: vbulavintsev/tentura-service:v0.0.5
    networks:
      - proxy
    ports:
      - 2080:2080/tcp
    environment:
      - "SERVER_NAME=https://dev.tentura.io"
      - "IMAGE_SERVER=https://dev.tentura.io"

volumes:
  pg_data:
