// Mocks generated by Mockito from annotations
// in tentura_server/test/api/controllers/graphql/invite_seed_resolver_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tentura_server/domain/capability/capability_evidence_models.dart'
    as _i5;
import 'package:tentura_server/domain/entity/invite_genealogy_graph_entity.dart'
    as _i2;
import 'package:tentura_server/domain/port/invite_genealogy_repository_port.dart'
    as _i6;
import 'package:tentura_server/domain/port/invite_seed_prompt_port.dart' as _i4;
import 'package:tentura_server/domain/port/mutating_unit_of_work_port.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInviteGenealogyGraphEntity_0 extends _i1.SmartFake
    implements _i2.InviteGenealogyGraphEntity {
  _FakeInviteGenealogyGraphEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInviteGenealogyChildrenPageEntity_1 extends _i1.SmartFake
    implements _i2.InviteGenealogyChildrenPageEntity {
  _FakeInviteGenealogyChildrenPageEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InviteSeedPromptPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInviteSeedPromptPort extends _i1.Mock
    implements _i4.InviteSeedPromptPort {
  MockInviteSeedPromptPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.PromptState?> stateFor({
    required String? inviterId,
    required String? inviteeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#stateFor, [], {
              #inviterId: inviterId,
              #inviteeId: inviteeId,
            }),
            returnValue: _i3.Future<_i5.PromptState?>.value(),
          )
          as _i3.Future<_i5.PromptState?>);

  @override
  _i3.Future<void> insertPending({
    required String? inviterId,
    required String? inviteeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertPending, [], {
              #inviterId: inviterId,
              #inviteeId: inviteeId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAnswered({
    required String? inviterId,
    required String? inviteeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAnswered, [], {
              #inviterId: inviterId,
              #inviteeId: inviteeId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markSkipped({
    required String? inviterId,
    required String? inviteeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markSkipped, [], {
              #inviterId: inviterId,
              #inviteeId: inviteeId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [InviteGenealogyRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInviteGenealogyRepositoryPort extends _i1.Mock
    implements _i6.InviteGenealogyRepositoryPort {
  MockInviteGenealogyRepositoryPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> recordSignupEdge({
    required String? ancestorUserId,
    required DateTime? ancestorUserCreatedAt,
    required String? descendantUserId,
    required DateTime? descendantUserCreatedAt,
    required String? invitationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordSignupEdge, [], {
              #ancestorUserId: ancestorUserId,
              #ancestorUserCreatedAt: ancestorUserCreatedAt,
              #descendantUserId: descendantUserId,
              #descendantUserCreatedAt: descendantUserCreatedAt,
              #invitationId: invitationId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> inviterOf(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#inviterOf, [userId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i2.InviteGenealogyGraphEntity> fetchLineage({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLineage, [], {#userId: userId}),
            returnValue: _i3.Future<_i2.InviteGenealogyGraphEntity>.value(
              _FakeInviteGenealogyGraphEntity_0(
                this,
                Invocation.method(#fetchLineage, [], {#userId: userId}),
              ),
            ),
          )
          as _i3.Future<_i2.InviteGenealogyGraphEntity>);

  @override
  _i3.Future<_i2.InviteGenealogyGraphEntity> fetchLineageBetween({
    required String? viewerId,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLineageBetween, [], {
              #viewerId: viewerId,
              #targetId: targetId,
            }),
            returnValue: _i3.Future<_i2.InviteGenealogyGraphEntity>.value(
              _FakeInviteGenealogyGraphEntity_0(
                this,
                Invocation.method(#fetchLineageBetween, [], {
                  #viewerId: viewerId,
                  #targetId: targetId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.InviteGenealogyGraphEntity>);

  @override
  _i3.Future<_i2.InviteGenealogyChildrenPageEntity> fetchChildren({
    required String? viewerId,
    required String? nodeKey,
    required int? limit,
    DateTime? afterCreatedAt,
    String? afterNodeKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchChildren, [], {
              #viewerId: viewerId,
              #nodeKey: nodeKey,
              #limit: limit,
              #afterCreatedAt: afterCreatedAt,
              #afterNodeKey: afterNodeKey,
            }),
            returnValue:
                _i3.Future<_i2.InviteGenealogyChildrenPageEntity>.value(
                  _FakeInviteGenealogyChildrenPageEntity_1(
                    this,
                    Invocation.method(#fetchChildren, [], {
                      #viewerId: viewerId,
                      #nodeKey: nodeKey,
                      #limit: limit,
                      #afterCreatedAt: afterCreatedAt,
                      #afterNodeKey: afterNodeKey,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.InviteGenealogyChildrenPageEntity>);

  @override
  _i3.Future<Map<String, int>> fetchChildCounts({
    required List<String>? nodeKeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchChildCounts, [], {#nodeKeys: nodeKeys}),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}

/// A class which mocks [MutatingUnitOfWorkPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockMutatingUnitOfWorkPort extends _i1.Mock
    implements _i7.MutatingUnitOfWorkPort {
  MockMutatingUnitOfWorkPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T> run<T>({
    required _i3.Future<T> Function()? action,
    String? actorUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#run, [], {
              #action: action,
              #actorUserId: actorUserId,
            }),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#run, [], {
                      #action: action,
                      #actorUserId: actorUserId,
                    }),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(#run, [], {
                    #action: action,
                    #actorUserId: actorUserId,
                  }),
                ),
          )
          as _i3.Future<T>);
}
