name: tentura_server
description: Tentura server API
publish_to: none

version: 0.2.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  tentura_root:
    path: ../../

  args: ^2.7.0
  uuid: ^4.4.2
  meta: ^1.16.0
  faker: ^2.2.0
  image: ^4.5.4
  minio: ^3.5.7
  drift: ^2.26.1
  get_it: ^8.0.3
  jaspr: ^0.18.2
  latlong2: ^0.9.1
  postgres: ^3.5.6
  injectable: ^2.5.0
  collection: ^1.19.1
  shelf_plus: ^1.10.1
  blurhash_dart: ^1.2.1
  angel3_graphql: ^8.3.0
  drift_postgres: ^1.3.0
  graphql_schema2: ^6.3.0
  graphql_server2: ^6.3.0
  shelf_multipart: ^2.0.1
  dart_jsonwebtoken: ^3.2.0
  freezed_annotation: ^3.0.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  test: ^1.26.0
  freezed: ^3.0.6
  drift_dev: ^2.26.1
  build_runner: ^2.4.15
  jaspr_builder: ^0.18.2
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0
  build_web_compilers: ^4.1.5
  injectable_generator: ^2.6.2

jaspr:
  mode: server
