name: tentura_server
description: Tentura server API
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  uuid:
  get_it:
  logger:
  sentry:
  injectable:

  jaspr: ^0.16.2
  postgres: ^3.4.4
  shelf_plus: ^1.10.0
  dart_jsonwebtoken: ^2.14.2

dev_dependencies:
  build_runner:
  json_serializable:
  very_good_analysis:
  injectable_generator:

  jaspr_builder: ^0.16.2
  build_web_compilers: ^4.1.0

jaspr:
  mode: server
