// Regenerates lib/features/emoji/domain/emoji_catalog_data.dart from a local
// copy of the `emojibase-data` npm package (MIT, https://emojibase.dev).
//
// Usage (from packages/client):
//   npm pack emojibase-data && tar xzf emojibase-data-*.tgz
//   dart run tool/generate_emoji_catalog.dart package
//
// Each emoji becomes one line: `<emoji>\t<en shortcodes>\t<ru words>`, both
// lists space-separated. English shortcodes are the union of the GitHub and
// Slack (iamcal) presets; Russian words come from the CLDR-native shortcode
// and the Russian tags, so `:улыб` finds 😄.

import 'dart:convert';
import 'dart:io';

const _outPath = 'lib/features/emoji/domain/emoji_catalog_data.dart';

/// emojibase group 2 is "component" (skin tones, hair) — not standalone.
const _componentGroup = 2;

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/generate_emoji_catalog.dart <dir>');
    exit(64);
  }
  final root = args.single;
  List<dynamic> readList(String path) =>
      jsonDecode(File('$root/$path').readAsStringSync()) as List<dynamic>;
  Map<String, dynamic> readMap(String path) =>
      jsonDecode(File('$root/$path').readAsStringSync())
          as Map<String, dynamic>;
  List<String> codes(Object? value) => switch (value) {
    final String s => [s],
    final List<dynamic> l => l.cast<String>(),
    _ => const [],
  };

  final en = readList('en/data.json').cast<Map<String, dynamic>>();
  final ru = {
    for (final e in readList('ru/compact.json').cast<Map<String, dynamic>>())
      e['hexcode'] as String: e,
  };
  final github = readMap('en/shortcodes/github.json');
  final slack = readMap('en/shortcodes/iamcal.json');
  final ruNames = readMap('ru/shortcodes/cldr-native.json');

  final rows = en.where((e) {
    final group = e['group'];
    return group is int && group != _componentGroup;
  }).toList()..sort((a, b) => (a['order'] as int).compareTo(b['order'] as int));

  final lines = <String>[];
  for (final e in rows) {
    final hex = e['hexcode'] as String;
    final shortcodes = <String>{
      ...codes(github[hex]),
      ...codes(slack[hex]),
    }.map((s) => s.toLowerCase()).toList();
    if (shortcodes.isEmpty) continue;
    final ruWords = <String>{
      for (final name in codes(ruNames[hex])) ...name.split('_'),
      ...((ru[hex]?['tags'] as List<dynamic>?) ?? const []).cast<String>(),
    }.map((w) => w.toLowerCase().replaceAll('ё', 'е')).where(_isWord);
    for (final field in [...shortcodes, ...ruWords]) {
      if (field.contains(RegExp(r'[\s\t]'))) {
        throw StateError('whitespace in "$field" for $hex');
      }
    }
    lines.add(
      '${_emoji(e)}\t${shortcodes.join(' ')}\t${ruWords.join(' ')}',
    );
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_emoji_catalog.dart — do not edit.')
    ..writeln('// Source: emojibase-data (MIT), https://emojibase.dev')
    ..writeln()
    ..writeln(
      r'/// One emoji per line: `<emoji>\t<en shortcodes>\t<ru words>`.',
    )
    ..writeln("const kEmojiCatalogData = '''")
    ..writeln(lines.join('\n'))
    ..writeln("''';");
  File(_outPath).writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${lines.length} emoji to $_outPath');
}

/// emojibase spells emoji-presentation singles with a redundant VS16
/// (`👍` + U+FE0F); drop it so we insert what keyboards insert.
String _emoji(Map<String, dynamic> e) {
  final emoji = e['emoji'] as String;
  final core = emoji.runes.where((r) => r != 0xFE0F).toList();
  return e['type'] == 1 && core.length == 1
      ? String.fromCharCodes(core)
      : emoji;
}

bool _isWord(String w) => w.length >= 2 && !w.contains(RegExp(r'\s'));
