#!/usr/bin/env bash
# Writes packages/landing/config.local.js from repo-root .env (Google OAuth).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LANDING_DIR="$ROOT/packages/landing"
OUT="$LANDING_DIR/config.local.js"

eval "$(bash "$ROOT/scripts/resolve_local_web_config.sh" --export)"

google_enabled='false'
if [[ -n "${GOOGLE_CLIENT_ID// }" ]]; then
  google_enabled='true'
fi
email_only_qa="${LANDING_EMAIL_ONLY_QA:-false}"
if [[ "$email_only_qa" != 'true' ]]; then
  email_only_qa='false'
fi

cat >"$OUT" <<EOF
// Generated by scripts/sync-landing-local-config.sh — do not commit.
window.TENTURA = Object.assign(window.TENTURA || {}, {
  googleEnabled: ${google_enabled},
  emailOnlyQa: ${email_only_qa},
});
EOF

echo "Wrote $OUT (googleEnabled=${google_enabled}, emailOnlyQa=${email_only_qa})"
