// Mocks generated by Mockito 5.4.6 from annotations
// in tentura_server/test/api/controllers/websocket/websocket_realtime_protocol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tentura_root/domain/enums.dart' as _i14;
import 'package:tentura_server/domain/entity/account_credential_entity.dart'
    as _i3;
import 'package:tentura_server/domain/entity/asserted_contact.dart' as _i7;
import 'package:tentura_server/domain/entity/invitation_entity.dart' as _i4;
import 'package:tentura_server/domain/entity/invite_accepted_notification_intent.dart'
    as _i11;
import 'package:tentura_server/domain/entity/user_entity.dart' as _i2;
import 'package:tentura_server/domain/entity/user_presence_entity.dart' as _i13;
import 'package:tentura_server/domain/port/beacon_room_co_participant_lookup_port.dart'
    as _i16;
import 'package:tentura_server/domain/port/invitation_repository_port.dart'
    as _i9;
import 'package:tentura_server/domain/port/invite_accepted_notification_port.dart'
    as _i10;
import 'package:tentura_server/domain/port/user_presence_repository_port.dart'
    as _i12;
import 'package:tentura_server/domain/port/user_repository_port.dart' as _i5;
import 'package:tentura_server/domain/port/vote_user_friendship_lookup_port.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountCredentialEntity_1 extends _i1.SmartFake
    implements _i3.AccountCredentialEntity {
  _FakeAccountCredentialEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvitationEntity_2 extends _i1.SmartFake
    implements _i4.InvitationEntity {
  _FakeInvitationEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepositoryPort extends _i1.Mock
    implements _i5.UserRepositoryPort {
  @override
  _i6.Future<_i2.UserEntity> create({
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#create, [], {
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#create, [], {
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> createInvited({
    required String? invitationId,
    required String? publicKey,
    required String? displayName,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvited, [], {
              #invitationId: invitationId,
              #publicKey: publicKey,
              #displayName: displayName,
              #handle: handle,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvited, [], {
                  #invitationId: invitationId,
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvited, [], {
                  #invitationId: invitationId,
                  #publicKey: publicKey,
                  #displayName: displayName,
                  #handle: handle,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> createWithCredential({
    required _i3.CredentialType? type,
    required String? identifier,
    required String? displayName,
    String? handle,
    Map<String, Object?>? publicData,
    List<_i7.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWithCredential, [], {
              #type: type,
              #identifier: identifier,
              #displayName: displayName,
              #handle: handle,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createWithCredential, [], {
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createWithCredential, [], {
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> createInvitedWithCredential({
    required String? invitationId,
    required _i3.CredentialType? type,
    required String? identifier,
    required String? displayName,
    String? handle,
    Map<String, Object?>? publicData,
    List<_i7.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvitedWithCredential, [], {
              #invitationId: invitationId,
              #type: type,
              #identifier: identifier,
              #displayName: displayName,
              #handle: handle,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvitedWithCredential, [], {
                  #invitationId: invitationId,
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#createInvitedWithCredential, [], {
                  #invitationId: invitationId,
                  #type: type,
                  #identifier: identifier,
                  #displayName: displayName,
                  #handle: handle,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> getByPublicKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getByPublicKey, [publicKey]),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByPublicKey, [publicKey]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByPublicKey, [publicKey]),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> getByCredential({
    required String? type,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByCredential, [], {
              #type: type,
              #identifier: identifier,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByCredential, [], {
                  #type: type,
                  #identifier: identifier,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#getByCredential, [], {
                  #type: type,
                  #identifier: identifier,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<List<_i3.AccountCredentialEntity>> listCredentials({
    required String? accountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listCredentials, [], {#accountId: accountId}),
            returnValue: _i6.Future<List<_i3.AccountCredentialEntity>>.value(
              <_i3.AccountCredentialEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i3.AccountCredentialEntity>>.value(
                  <_i3.AccountCredentialEntity>[],
                ),
          )
          as _i6.Future<List<_i3.AccountCredentialEntity>>);

  @override
  _i6.Future<_i3.AccountCredentialEntity> addCredential({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCredential, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
            }),
            returnValue: _i6.Future<_i3.AccountCredentialEntity>.value(
              _FakeAccountCredentialEntity_1(
                this,
                Invocation.method(#addCredential, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.AccountCredentialEntity>.value(
                  _FakeAccountCredentialEntity_1(
                    this,
                    Invocation.method(#addCredential, [], {
                      #accountId: accountId,
                      #type: type,
                      #identifier: identifier,
                      #publicData: publicData,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.AccountCredentialEntity>);

  @override
  _i6.Future<void> removeCredential({
    required String? accountId,
    required String? credentialId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeCredential, [], {
              #accountId: accountId,
              #credentialId: credentialId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> linkCredentialWithContacts({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
    List<_i7.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkCredentialWithContacts, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#linkCredentialWithContacts, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#linkCredentialWithContacts, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.AccountCredentialEntity> linkCredentialToAccountStrict({
    required String? accountId,
    required _i3.CredentialType? type,
    required String? identifier,
    Map<String, Object?>? publicData,
    List<_i7.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkCredentialToAccountStrict, [], {
              #accountId: accountId,
              #type: type,
              #identifier: identifier,
              #publicData: publicData,
              #contacts: contacts,
            }),
            returnValue: _i6.Future<_i3.AccountCredentialEntity>.value(
              _FakeAccountCredentialEntity_1(
                this,
                Invocation.method(#linkCredentialToAccountStrict, [], {
                  #accountId: accountId,
                  #type: type,
                  #identifier: identifier,
                  #publicData: publicData,
                  #contacts: contacts,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.AccountCredentialEntity>.value(
                  _FakeAccountCredentialEntity_1(
                    this,
                    Invocation.method(#linkCredentialToAccountStrict, [], {
                      #accountId: accountId,
                      #type: type,
                      #identifier: identifier,
                      #publicData: publicData,
                      #contacts: contacts,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.AccountCredentialEntity>);

  @override
  _i6.Future<String?> findCredentialId({
    required _i3.CredentialType? type,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findCredentialId, [], {
              #type: type,
              #identifier: identifier,
            }),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> addVerifiedContacts({
    required String? accountId,
    required _i3.CredentialType? source,
    List<_i7.AssertedContact>? contacts = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addVerifiedContacts, [], {
              #accountId: accountId,
              #source: source,
              #contacts: contacts,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> update({
    required String? id,
    String? displayName,
    String? description,
    String? imageId,
    bool? dropImage = false,
    bool? setHandle = false,
    String? handle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #displayName: displayName,
              #description: description,
              #imageId: imageId,
              #dropImage: dropImage,
              #setHandle: setHandle,
              #handle: handle,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteById({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {#id: id}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> bindMutual({
    required String? invitationId,
    required String? userId,
    bool? bindFriendship = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bindMutual, [], {
              #invitationId: invitationId,
              #userId: userId,
              #bindFriendship: bindFriendship,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [InvitationRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationRepositoryPort extends _i1.Mock
    implements _i9.InvitationRepositoryPort {
  @override
  _i6.Future<_i4.InvitationEntity?> getById({required String? invitationId}) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [], {#invitationId: invitationId}),
            returnValue: _i6.Future<_i4.InvitationEntity?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i4.InvitationEntity?>.value(),
          )
          as _i6.Future<_i4.InvitationEntity?>);

  @override
  _i6.Future<_i4.InvitationEntity> create({
    required String? issuerId,
    required String? addresseeName,
    String? beaconId,
    String? parentForwardEdgeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #issuerId: issuerId,
              #addresseeName: addresseeName,
              #beaconId: beaconId,
              #parentForwardEdgeId: parentForwardEdgeId,
            }),
            returnValue: _i6.Future<_i4.InvitationEntity>.value(
              _FakeInvitationEntity_2(
                this,
                Invocation.method(#create, [], {
                  #issuerId: issuerId,
                  #addresseeName: addresseeName,
                  #beaconId: beaconId,
                  #parentForwardEdgeId: parentForwardEdgeId,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.InvitationEntity>.value(
              _FakeInvitationEntity_2(
                this,
                Invocation.method(#create, [], {
                  #issuerId: issuerId,
                  #addresseeName: addresseeName,
                  #beaconId: beaconId,
                  #parentForwardEdgeId: parentForwardEdgeId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.InvitationEntity>);

  @override
  _i6.Future<_i4.InvitationEntity> updateAddresseeName({
    required String? invitationId,
    required String? userId,
    required String? addresseeName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddresseeName, [], {
              #invitationId: invitationId,
              #userId: userId,
              #addresseeName: addresseeName,
            }),
            returnValue: _i6.Future<_i4.InvitationEntity>.value(
              _FakeInvitationEntity_2(
                this,
                Invocation.method(#updateAddresseeName, [], {
                  #invitationId: invitationId,
                  #userId: userId,
                  #addresseeName: addresseeName,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.InvitationEntity>.value(
              _FakeInvitationEntity_2(
                this,
                Invocation.method(#updateAddresseeName, [], {
                  #invitationId: invitationId,
                  #userId: userId,
                  #addresseeName: addresseeName,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.InvitationEntity>);

  @override
  _i6.Future<bool> deleteById({
    required String? invitationId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {
              #invitationId: invitationId,
              #userId: userId,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [InviteAcceptedNotificationPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockInviteAcceptedNotificationPort extends _i1.Mock
    implements _i10.InviteAcceptedNotificationPort {
  @override
  _i6.Future<void> notifyInviteAccepted(
    _i11.InviteAcceptedNotificationIntent? intent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyInviteAccepted, [intent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserPresenceRepositoryPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPresenceRepositoryPort extends _i1.Mock
    implements _i12.UserPresenceRepositoryPort {
  @override
  _i6.Future<_i13.UserPresenceEntity?> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i6.Future<_i13.UserPresenceEntity?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i13.UserPresenceEntity?>.value(),
          )
          as _i6.Future<_i13.UserPresenceEntity?>);

  @override
  _i6.Future<void> update(
    String? userId, {
    DateTime? lastSeenAt,
    DateTime? lastNotifiedAt,
    _i14.UserPresenceStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [userId],
              {
                #lastSeenAt: lastSeenAt,
                #lastNotifiedAt: lastNotifiedAt,
                #status: status,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [VoteUserFriendshipLookupPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteUserFriendshipLookupPort extends _i1.Mock
    implements _i15.VoteUserFriendshipLookupPort {
  @override
  _i6.Future<Set<String>> reciprocalPositivePeerIds({
    required String? viewerId,
    required Iterable<String>? peerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reciprocalPositivePeerIds, [], {
              #viewerId: viewerId,
              #peerIds: peerIds,
            }),
            returnValue: _i6.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i6.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i6.Future<Set<String>>);

  @override
  _i6.Future<bool> isReciprocalSubscribe({
    required String? viewerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isReciprocalSubscribe, [], {
              #viewerId: viewerId,
              #peerId: peerId,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isSubscribedTo({
    required String? viewerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribedTo, [], {
              #viewerId: viewerId,
              #peerId: peerId,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [BeaconRoomCoParticipantLookupPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeaconRoomCoParticipantLookupPort extends _i1.Mock
    implements _i16.BeaconRoomCoParticipantLookupPort {
  @override
  _i6.Future<Set<String>> coParticipantPeerIds({
    required String? viewerId,
    required Iterable<String>? peerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#coParticipantPeerIds, [], {
              #viewerId: viewerId,
              #peerIds: peerIds,
            }),
            returnValue: _i6.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i6.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i6.Future<Set<String>>);
}
