name: share_handler_multi
description: Dart package for multiplatform usage share_handler
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ^3.24.2

dependencies:
  share_handler: ^0.0.21
