name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.0.5

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ^3.32.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tentura:
    path: ../client

  get_it: ^8.0.3
  logger: ^2.5.0
  injectable: ^2.5.0
  widgetbook: ^3.14.2
  google_fonts: ^6.2.1
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.15
  very_good_analysis: ^8.0.0
  injectable_generator: ^2.6.2
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true
