name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  tentura:
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.4
  very_good_analysis: ^6.0.0
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
