name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.0.3

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ^3.29.3

dependencies:
  tentura:
    path: ../client
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^8.0.3
  logger: ^2.5.0
  injectable: ^2.5.0
  google_fonts: ^6.2.1
  widgetbook: ^3.13.1
  widgetbook_annotation: ^3.4.0

dev_dependencies:
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.2
  widgetbook_generator: ^3.12.0

flutter:
  uses-material-design: true
